### DISCUSSION TITLE
How to enable registerHealthIndicator programatically

### DISCUSSION THREAD

**Discussion by Krith-10** [resilience4j/resilience4j#1906] [Q&A]
Hi,
I noticed that https://resilience4j.readme.io/docs/getting-started-3#health-endpoint 
```
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
```
registerHealthIndicator can be set to true via properties and this works, or else the value would be [false by default](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/health/CircuitBreakersHealthIndicator.java#L103)

I had created the circuit breaker programmatically as `@Bean` 

```
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
                .slidingWindowType(SlidingWindowType.TIME_BASED)
                .slidingWindowSize(10)
                .minimumNumberOfCalls(6)
                .failureRateThreshold(50)
                .slowCallDurationThreshold(Duration.ofSeconds(10))
                .slowCallRateThreshold(50)
                .build();
```
and wanted to enable `registerHealthIndicator` to `true`.  Is there any method in the [CircuitBreakerConfig](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerConfig.java#L100) to enable the HealthIndicator to true. Or is there any other workaround?

Thanks!
