### DISCUSSION TITLE
Circuit Breaker calls the method even in the OPEN state

### DISCUSSION THREAD

**Discussion by vittaliy79** [resilience4j/resilience4j#1917] [Q&A]
Hi,
I have an issue with the ReactiveResilience4JCircuitBreaker impementation for the Mono methods. 
I have a big project which uses Resilience4j for the Circuit Breaker implementation and I've noticed the method wrapped by the Circuit Breaker is called even when in OPEN state. The wrapper method is throwing the CallNotPermitted exception but the actual method still called which is not what I need. 
By the spec Circuit Breaker should reject calls in OPEN state so I don't what the method to be called at all.
Also I'm using several CircuitBreakers to be called in order when previous is failed.
My current implementation is the following:
```
public  Mono<ResponseClass> sendWithCircuitBreaker(final String clientId, String request){
 final ReactiveCircuitBreaker circuitBreaker = circuitBreakerProvider.getCircuitBreaker(clientId);
 final String fallbackClientId = circuitBreakerProvider.getFallbackClientId(clientId);

     return   connectionService.send(request)
                .transform(it -> circuitBreaker.run(it, throwable -> {
                    if (throwable instanceof CallNotPermittedException) {
                        return this.sendWithCircuitBreaker(fallbackClientId, request);
                    } else {
                        return Mono.error(throwable);
                    }
                }));
}
```
where the 
* **fallbackClientId** is the next Circuit Breaker ID in the CBs list
* **circuitBreakerProvider** - is the custom class to provide Circuit Breaker from the generated list

The configuration is the following:
```
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 120000
        failureRateThreshold: 50
        eventConsumerBufferSize: 100
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 50s
```

Could you advise what is incorrect in this implementation?
