### DISCUSSION TITLE
Configuring TimeLimiter in a Multi-Module Spring Boot Application

### DISCUSSION THREAD

**Discussion by lmrossonero** [resilience4j/resilience4j#2031] [Q&A]
I have a multi-module Spring Boot application that uses Hystrix and Feign. And we are moving to resilience4j. Below is the main configuration property I'm using:

```
hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 1500
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 40

feign.hystrix.enabled: true
```

In my application, I have over a hundred Feign clients, each containing numerous methods. I'm looking for a way to configure a TimeLimiter for all of these clients without having to set @TimeLimiter on each individual method.

Can anyone suggest an efficient way to achieve this? Thank you!
