### ISSUE TITLE
Fallback method not called while using Spring annotations approach

### ISSUE THREAD

**Issue by spatanjali** [resilience4j/resilience4j#1048]
Resilience4j version: 1.4.0 (also have tried on 1.5.0)

Java version: 1.8.0

This topic has been raised before at #1037 but considering that the circumstances might be different, I've raised a new issue.

I've tried to use Annotation based approach to the CircuitBreaker. Unfortunately the fallback method is not getting triggered. I also observe via metrics (resilience4j.circuitbreaker.calls) that all the calls are considered as failure but with ignored exceptions.

Following are the code & config. Please let me know if I've got something wrong.

**Config**
```
 resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 8
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.io.IOException
  instances:
    acdlabsservice:
      baseConfig: default
    camsoftservice:
      baseConfig: default
```
 
**CircuitBreakerComponent**
```
   @Component
   public class SubServiceClient {

    @CircuitBreaker(name = "cservice", fallbackMethod = "requestCServiceFallback")
    public Response requestCService(String name){
        try {
            throw new IOException();
        } catch (Exception e) {
            System.out.println("Throw C Service IOException");
        }
        return null;
    }

    public Response requestCServiceFallback(String name, IOException e){
        System.out.println("Triggered cService Fallback");
        return new Response();
    }
   }
```

**CircuitBreaker Supplier Execution**
```
@Autowired
private final SubServiceClient subServiceClient;
..
..
subServiceClient.requestAcdLabsService("name");
```

**POM.xml**
```
      <parent>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-parent</artifactId>
          <version>2.3.1.RELEASE</version>
          <relativePath /> <!-- lookup parent from repository -->
      </parent>
..
..

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-all</artifactId>
            <version>1.4.0</version>
        </dependency>

```
