### ISSUE TITLE
TIME_BASED window not recording FailureRate

### ISSUE THREAD

**Issue by ankushbbbr** [resilience4j/resilience4j#1070]
Resilience4j version: 1.5.0

Java version: 8

I was testing resilience4j circuitBreaker with TIME_BASED sliding window with the following configuration - 

    public interface BackendService {
        String doSomething() throws IOException;
    }
    public static void main(String[] args) throws Exception {
        CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(10)
                .waitDurationInOpenState(Duration.ofMillis(1000))
                .permittedNumberOfCallsInHalfOpenState(5)
                .slidingWindowType(SlidingWindowType.TIME_BASED)
                .slidingWindowSize(1)
                .recordExceptions(IOException.class, TimeoutException.class, RuntimeException.class)
                .build();

        CircuitBreakerRegistry circuitBreakerRegistry =
                CircuitBreakerRegistry.of(circuitBreakerConfig);
        
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("breaker");
        circuitBreaker.getEventPublisher().onEvent(event->System.out.println(event));
        BackendService backendServiceError = new BackendService() {

            @Override
            public String doSomething() throws IOException{
                System.out.println("Error ckt function");
                throw new IOException();
            }
        };

        for(int i=0;i<1000;i++) {
            String result;
            try {
                result = circuitBreaker.executeCheckedSupplier(()-> backendServiceError.doSomething());
                System.out.println(i + " " + result);
            } catch (Throwable e) {
                System.out.println(e.toString());
            } finally {
                System.out.println(", #failed calls = " + circuitBreaker.getMetrics().getNumberOfFailedCalls()
                    + " #failure rate = " + circuitBreaker.getMetrics().getFailureRate());
            }
            Thread.sleep(10);
        }
    }
Throughput is 100 calls/sec and with sliding time window of 1 sec, failureRate stays at -1 , with max 80-90 failures being recorded in one time window. This behavior is not intended and in resilience4j version 1.5, there's no `minimumThroughput` configurable param for CircuitBreakerConfig to avoid this behavior when throughput is low.

**Comment by RobWin** [comment]
`minimumThroughput`  ==>  `minimumNumberOfCalls`.
The default is 100, you can decrease it.

**Comment by koidearepos** [comment]
Hi, I use resillemce4j, but circuit breaker not count fail request. I spent 4 days for it. ow can I fix it.

```
resilience4j:
  circuitbreaker:
    configs:
      defaultCircuitbreaker:
        slidingWindowType: COUNT_BASED #Kayıt altına alınan data kıstası. Saniye olarakta belirlenebilmektedir.
        slidingWindowSize: 5 #Son x datanın dikkate alınmasını sağlar.
        minimumNumberOfCalls: 5 #Asgari kayıt sayısını belirler. Bu kayıt sayısından sonra algoritmalar çalışacaktır.
        permittedNumberOfCallsInHalfOpenState: 2 #Sigora yarı açıkken yapılacak max kayıt sayısı.
        automaticTransitionFromOpenToHalfOpenEnabled: true #Sigortanın açık konumdan yarı-açık konuma gelmesini üsrecinin atomatize edilmesi sağlar.
        failureRateThreshold: 50 #% cinsinden ne kadar bir fail oranı olursa sigorta açık konuma gelecek bilgisi girilir.
        waitDurationInOpenState: 60s #Açık olan devre saniye sonra yarı açık hal gelecektir.
        slowCallDurationThreshold: 30s #Saniye üzerinde dönen request'leri yavaş olarak kabul edecektir.
        slowCallRateThreshold: 90 #Yavaş request sayısı %x'i aşarsa sigorta yarı-açık konuma gelecektir.
        registerHealthIndicator: true
    instances:
      fallbackAuth:
        baseConfig: defaultCircuitbreaker
      fallbackUser:
        baseConfig: defaultCircuitbreaker
      fallbackEvent:
        baseConfig: defaultCircuitbreaker
      fallbackComment:
        baseConfig: defaultCircuitbreaker
      fallbackParticipant:
        baseConfig: defaultCircuitbreaker
  timelimiter:
    configs:
      defaultTimelimiter:
        timeoutDuration: 20s
    instances:
      fallbackAuth:
        baseConfig: defaultTimelimiter
      fallbackUser:
        baseConfig: defaultTimelimiter
      fallbackEvent:
        baseConfig: defaultTimelimiter
      fallbackComment:
        baseConfig: defaultTimelimiter
      fallbackParticipant:
        baseConfig: defaultTimelimiter
```

When I throw exception, I see in log like this:
CircuitBreaker 'fallbackAuth' recorded a successful call
