### ISSUE TITLE
Retry always happening twice irrespective of maxAttempts configuration value

### ISSUE THREAD

**Issue by spate214-ford** [resilience4j/resilience4j#1077]
Resilience4j version: resilience4j-spring-boot2:1.5.0

Java version: 11

I am trying to implement retry with circuit breaker. Below is the configurations. retry is configured with maxAttempts: 1. I am expecting it should retry once after the failure meaning total 2 calls. But it is retrying twice. Even if I increase maxAttempts to 3 or 4 it is retrying twice. Can you please check the configuration and let me know if anything is wrong.

configuration:

```
resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 5s
    instances:
      GetServicesCommand:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        timeoutDuration: 10
    instances:
      GetServicesCommand:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 1
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.net.SocketException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      GetServicesCommand:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
    instances:
      GetServicesCommand:
        baseConfig: default
```
