### ISSUE TITLE
Retry is not working for java.net.ConnectException 

### ISSUE THREAD

**Issue by Ankit-Mund** [resilience4j/resilience4j#1182]
Resilience4j version:1.5.0

Java version:1.8

I'm making a SOAP call inside a method, to a service that is down and returns java.net.ConnectException exception. I've annotated this method with Retry:
```
@Retry(name = SOAPCLIENT)
	public Acknowledgement getLoanStatus(CustomerRequest request) {
		//SOAP call to a server that's down, returns java.net.ConnectException
	}
```

I need to retry the SOAP call in this scenario, but Retry is not able to catch this exception. I've added this exception to retryExceptions in the yaml file as well.

Here's my Retry config in application.yml:
```
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 3
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.ConnectException
    instances:
        soapclient:
            baseConfig: default
```
Please advise how to proceed with this.
