### ISSUE TITLE
Retry max attempts configuration not resolved from base config

### ISSUE THREAD

**Issue by swalendzik** [resilience4j/resilience4j#1334]
Base configuration of max attemps is not resolved properly from base config here is an example
default-config has configured max attempts = 4
all-exceptions-config extends default-config and overrides only retryExceptions
maxAttempts configuration is not taken from baseConfig and it's resolved to 3, which is default

I did not test other configuration properties

configuration: 
```
resilience4j.retry:
  configs:
    default-config:
      maxAttempts: 4
      waitDuration: 100ms
      retryExceptionPredicate: io.github.resilience4j.circuitbreaker.RecordFailurePredicate
      retryExceptions:
        - java.io.IOException

    all-exceptions-config:
      baseConfig: default-config
      retryExceptions:
        - java.lang.Exception

  backends:
      retryBackendE:
         baseConfig: all-exceptions-config
```

following assertion fails on max attempt check
```
Retry overriddenException = retryRegistry.retry("retryBackendE");
assertThat(overriddenException.getRetryConfig().getMaxAttempts()).isEqualTo(4);
assertThat(overriddenException.getRetryConfig().getExceptionPredicate().test(new UnsupportedOperationException()))
            .isTrue();
```
