### ISSUE TITLE
resilience4j-spring-boot2: Create circuit breaker based on default configuration

### ISSUE THREAD

**Issue by Ferioney** [resilience4j/resilience4j#1378]
Resilience4j version: 1.6.1.

I have default resilience4j configuration:
```
resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 10000
            failureRateThreshold: 60
            eventConsumerBufferSize: 10
```

and some specific:
```
resilience4j.circuitbreaker:
    instances:
        backendA:
            slidingWindowSize: 50
```
In that case, the circuit breaker was created based on a specific configuration without using the default configuration. 
To override the default configuration I should use `baseConfig` property.

As for me it more reasonable to override the default configuration without `baseConfig` property. And in case, if  `baseConfig` is presented, doesn't override the default configuration and override configuration from `baseConfig` property. 

The same for all modules - TimeLimiter/Bulkhead/ThreadPoolBulkhead ets.
