### ISSUE TITLE
Configuring Retry predicates via yaml file not working, help

### ISSUE THREAD

**Issue by fherrera-automox** [resilience4j/resilience4j#1426]
Resilience4j version: 1.7.0, Java version: 15

Hi, I am trying to configure a Retry via spring boot yaml properties, but haven't found a way to configure the predicates. I looked at the examples from CircuitBreaker and at the RetryConfigurationProperties.InstanceProperties, then I tried with the following but does NOT work:

```
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 1
    resultPredicate: com.predicate.ResponseFailurePredicate
    retryExceptionPredicate: com.predicate.ResponseExceptionPredicate
    failAfterMaxAttempts: true

```

I am getting this error:
```
Description:
Failed to bind properties under 'resilience4j.retry.configs.resultpredicate' to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties:

    Reason: No converter found capable of converting from type [java.lang.String] to type [io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties]

Action:
Update your application's configuration
```

1) Is it possible to configure the Retry predicates via yaml properties ?
2) Any idea or hint how to do it ?

Would appreciate your help. Thanks,
Francisco
