### ISSUE TITLE
retry 3 times, circuit breaker not coming to open status.

### ISSUE THREAD

**Issue by prasathb** [resilience4j/resilience4j#1444]
Resilience4j version:1.7.0

Java version:11.0.2

My use case is: In case of first system error, retry should trigger first and if retry is successful, return the response to user else go to retry fallback. If no system error but business exception then circuit breaker should trigger and after failure threshold should move to open state and all call should route to circuit breaker fallback.

Here is my yml file:

```
resilience4j.circuitbreaker:
  configs:
    default:

      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 2
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 1s
      failureRateThreshold: 50

      recordExceptions:   
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpServerErrorException
        
resilience4j:
  circuitbreaker:
    instances:

      client1:
        baseConfig: default
      client2:
        baseConfig: default

    metrics:
      enabled: true

      legacy:
        enabled: true
 

  ratelimiter:
    instances:

      client1:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 100000
        limitForPeriod: 10

  retry:
    instances:
      client1:

        maxAttempts: 3
        waitDuration: 25

            retryExceptions:
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
              - java.util.concurrent.TimeoutException
              - java.io.IOException
              - 
             ignoreExceptions:
              - io.github.resilience4j.circuitbreaker.CallNotPermittedException


management:
  endpoint:
    health:
      show-components: always
```

below is the code where i have applied circuit breaker and retry logic:

```
	@Retry(name = "client1", fallbackMethod = "fallback_retry")
	@CircuitBreaker(name = "client1", fallbackMethod = "fallback_secondary")
	public String getBookList() {
		return restTemplate.getForObject(primaryUrl + "/recommended", String.class);
	}

	private String fallback_secondary(Exception e) {
		logger.error("fallback secondary , cause {}", e.toString());
		return restTemplate.getForObject(fallbackSecondaryUrl + "/recommended", String.class);
	}

	private String fallback_retry(Exception e) {
		logger.error("fallback retry , cause {}", e.toString());
		return "fallback retry";
	}
```

after retrying 3 times and if it is not system error, circuit breaker should trigger/activate. which is not happening. am i missing anything in my code or following wrong approach?
