### ISSUE TITLE
Issue with Kotlin-Micronaut

### ISSUE THREAD

**Issue by MaruthiRao** [resilience4j/resilience4j#1473]
Please find below code but it is not falling back. Can you please help on this?

 @Inject
    var httpClient: RxHttpClient? = null

    @CircuitBreaker(name = "carrier-service", fallbackMethod = "futureFallback")
    fun testMethod(): String? {
        return httpClient!!.toBlocking().retrieve("http://localhost:8081/carrier-service")
    }

    @Executable
    fun futureFallback(e : Exception): String? {
        return "This is my fallback plan"
    }

config
esilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 3
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 3
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordExceptions:
                - io.micronaut.http.client.exceptions.NoHostException
                - io.micronaut.http.client.exceptions.HttpClientException
                - io.netty.channel.AbstractChannel$AnnotatedConnectException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.UnknownHostException
                - java.net.ConnectException
                - java.net.SocketTimeoutException
                - org.springframework.web.client.ResourceAccessException
                - java.net.SocketException
    instances:
        carrier-service:
            baseConfig: default

**Comment by pollend** [comment]
there are some micronaut specific annoations are you using those: `io.github.resilience4j.micronaut.annotation`? there is a limitation with the annotation processor.

**Comment by MaruthiRao** [comment]
Hi Pollend

thsnks for the response. I think I am not using the annotation dependency. Shall I try using it? Also I will check out on groovy test case

**Comment by MaruthiRao** [comment]
Hi @pollend, I could not find the resilience4j.micronaut.annotation dependency. Mine is a maven Kotlin micronaut project. I could not find either in maven or graddle repository.

Any clue on fall back method...

**Comment by pollend** [comment]
its apart of the resilience4j-micronaut package. its under this namespace: `io.github.resilience4j.micronaut.annotation`. there is also this sample working project you can also look at: https://github.com/resilience4j/resilience4j-micronaut-demo  

do you have a demo of some kind I can look at?

**Comment by MaruthiRao** [comment]
Below is the Kotlin micronaut code which I have to fall back when I hit a end point -


------------------------
@Inject
var httpClient: RxHttpClient? = null

@CircuitBreaker(name = "carrier-service", fallbackMethod = "futureFallback")
fun testMethod(): String? {
    return httpClient!!.toBlocking().retrieve("http://localhost:8081/carrier-service")
}

@Executable
fun futureFallback(e : Exception): String? {
    return "This is my fallback plan"
}
--------------------------

Yaml configuration for above code


resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 3
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 3
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordExceptions:
                - io.micronaut.http.client.exceptions.NoHostException
                - io.micronaut.http.client.exceptions.HttpClientException
                - io.netty.channel.AbstractChannel$AnnotatedConnectException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.UnknownHostException
                - java.net.ConnectException
                - java.net.SocketTimeoutException
                - org.springframework.web.client.ResourceAccessException
                - java.net.SocketException
    instances:
        carrier-service:
            baseConfig: default


management:
    health:
        circuitbreakers.enabled: true
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
            show-components: always
            circuitbreakers.enabled: true

**Comment by pollend** [comment]
I don't see anything wrong, what version of micronaut are you running. I think this is configured from micronaut 2 last I worked on this.

**Comment by MaruthiRao** [comment]
Hi @pollend, micronaut version is 2.0.3

**Comment by inndranil1210** [comment]
Hey @pollend  I am facing the same issue with my project ( micronaut, java, resilience4j, maven). Could you please help?

**Comment by pollend** [comment]
I'll try some things over the weekend, probably try and make a sample project and see If I can reproduce the issue.  do you have a sample project that I can look at?

**Comment by inndranil1210** [comment]
I don't have sample project, I am using that in my enterprise application. I am afraid I can not share with you that.

**Comment by pollend** [comment]
@inndranil1210 one thought that occurred to me, did you double check your application.yml. here is the one from the sample app:

https://github.com/resilience4j/resilience4j-micronaut-demo/blob/master/src/main/resources/application.yml
```
resilience4j:
  circuitbreaker:
    enabled: true
    instances:
      backendA:
        baseConfig: default
      backendB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: PT5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordFailurePredicate: resilience4j.micronaut.demo.exception.RecordFailurePredicate
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: PT5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - io.micronaut.http.exceptions.HttpStatusException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - resilience4j.micronaut.demo.exception.BusinessException
      shared:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: PT1s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - resilience4j.micronaut.demo.exception.BusinessException
  retry:
    enabled: true
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        retryExceptions:
          - io.micronaut.http.exceptions.HttpStatusException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - resilience4j.micronaut.demo.exception.BusinessException
    instances:
      backendA:
        baseConfig: default
      backendB:
        baseConfig: default
  bulkhead:
    enabled: true
    configs:
      default:
        maxConcurrentCalls: 100
    instances:
      backendA:
        maxConcurrentCalls: 10
      backendB:
        maxWaitDuration: PT0.01S
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    enabled: true
    configs:
      default:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
    instances:
      backendA:
        baseConfig: default
      backendB:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
  ratelimiter:
    enabled: true
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      backendA:
        baseConfig: default
      backendB:
        limitForPeriod: 6
        limitRefreshPeriod: PT0.5S
        timeoutDuration: 3s
  timelimiter:
    enabled: true
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: PT2s
    instances:
      backendA:
        baseConfig: default
      backendB:
        baseConfig: default
```
