### ISSUE TITLE
CircuitBreaker on a fallback method using spring boot

### ISSUE THREAD

**Issue by mrwest1** [resilience4j/resilience4j#1506]
Resilience4j version: 1.7.0

Java version: 1.8.0_121

Spring Boot version: 2.5.1

Is it possible to have a `@CircuitBreaker` annotation on a fallback method? The idea would be to failover from calling a local service to call another data center and then to provide some kind of static message if the service is also having problems in the remote data center.

I can't seem to make it work. The testService circuit breaker is retrieved, but the testServiceFallback circuit breaker never gets retrieved, even when the testService one is open.

Code would looks like this

```
@Service
public class ServiceImpl implements Service {

    @Autowired
    RestTemplate restTemplate;

    @Bean
    RestTemplate restTemplate(){
      return new RestTemplate();
    }

    @Override
    @CircuitBreaker( name = "testService", fallbackMethod = "dataCenterFallback" )
    public String test( ) {
        return restTemplate.getForObject("http://" + localService + "/test", String.class);
    }

    @CircuitBreaker( name = "testServiceFallback", fallbackMethod = "finalFallback" )
    public String dataCenterFallback( Throwable t ) {
        return restTemplate.getForObject("http://" + remoteService + "/test", String.class);
    }

    public String finalFallback( Throwable t ) {
        return "Unavailable";
    }
}
```

Configuration in application.yml is:

```
resilience4j:
 circuitbreaker:
    instances:
      testService:
        slowCallDurationThreshold:  500
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
      testServiceFallback:
        slowCallDurationThreshold:  750
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
```
