### ISSUE TITLE
Issue with fallback method working in springboot

### ISSUE THREAD

**Issue by Schachte** [resilience4j/resilience4j#1526]
Resilience4j version:
1.7.0

Java version:
Java 11

My fallback isn't working for some reason. I have this working in another module, but looking for advice on how to debug a bit deeper. `SeedGraph` is throwing a TransientException (forcefully), but still I am not hitting the fallback. It's also never retrying. How can I start debugging or what are some recommendations to figure out if resilience4j is configured correctly? 

YAML
```
resilience4j.retry:
    configs:
        default:
            maxAttempts: 3
            waitDuration: 100
            retryExceptions:
                - com.thing.NonTransientException
                - com.thing.TransientException
    instances:
        processGraphSeed:
            identifier: processGraphSeed
            baseConfig: default
```

```java
  @Retry(name = "processGraphSeed", fallbackMethod = "handleSeedFailure")
  public void processGraphSeed(
      List<NodeInfo> nodeInfo,
      List<EdgeInfo> edgeInfo,
      List<ConsumerRecord<String, GraphComponent>> batch) throws TransientException {
           seedGraph(nodeInfo, edgeInfo);
       }

  public void handleSeedFailure(
      List<NodeInfo> nodeInfo,
      List<EdgeInfo> edgeInfo,
      List<ConsumerRecord<String, GraphComponent>> batch,
      TransientException e) {
      log.error(
          "Retries exceeded for the following topic: {} and offset: {}. Publishing record to DLQ",
          batch.get(0).topic(),
          batch.get(0).offset());
      meterRegistry.counter(
          PROCESSING_FAILURE, "type", "error", "exception", e.getClass().getSimpleName());

      // dlq handler
  }
````
