### ISSUE TITLE
Resilience4J Kotlin coroutines define fallback method

### ISSUE THREAD

**Issue by Pavlmits** [resilience4j/resilience4j#1542]
Resilience4j version: 1.7.1

I have a spring boot application written in Kotlin with coroutines and I want to add Resilience4J for timelimiter and circuit breaker capabilities. I want to keep my code isolated from resilience4j specific dependency and I thought to create a class with the appropriate code and inject that class whenever is necessary. This class with automatically get the configuration properties from the application.yml file.

The abstraction that will be used in my code:

```
@Component
class CircuitBreakerHelper(
    private val timeLimiterRegistry: TimeLimiterRegistry,
    private val circuitBreakerRegistry: CircuitBreakerRegistry
) {

    suspend fun <T> run(commandKey: String, block: suspend () -> T): T {
        LoggerFactory.getLogger(javaClass.name).info("Time limiter $commandKey = ${timeLimiterRegistry.timeLimiter(commandKey).timeLimiterConfig.timeoutDuration}")
        val timeLimitedBlock = timeLimiterRegistry.timeLimiter(commandKey).decorateSuspendFunction(block)

        val circuitBreakingTimeLimitedBlock = circuitBreakerRegistry
            .circuitBreaker(commandKey)
            .decorateSuspendFunction(timeLimitedBlock)

        return circuitBreakingTimeLimitedBlock()
    }

    companion object {
        const val COMMAND_1 = "command1",
        const val COMMAND_2 = "command2"
    }
}
```

Usage in my code:

```
  suspend fun createAlbum(query: String): Album {
            return circuitBreakerHelper.run(CircuitBreakerHelper.COMMAND_1) {
                webclient.post().uri("/albums")
                    .accept(MediaType.APPLICATION_JSON)
                    .bodyValue(query)
                    .retrieve()
                    .bodyToMono<Album>()
                    .awaitFirstOrNull()
            }

        }
```

The application.yml file:

```
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    command1:
      baseConfig: default


resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
  instances:
    command1:
      timeoutDuration: 3s
    command2:
      timeoutDuration: 2s

```

So the main idea is that someone can inject the CircuitBreakerHelper and just pass the command key and the suspend code block. But if the circuit breaker will open I want to have a fallback method to run without using spring boot annotations from https://resilience4j.readme.io/v0.17.0/docs/getting-started-3#annotations. 

My goal is to make something like:

```
@Component
class CircuitBreakerHelper(
    private val timeLimiterRegistry: TimeLimiterRegistry,
    private val circuitBreakerRegistry: CircuitBreakerRegistry
) {

    suspend fun <T> run(commandKey: String, block: suspend () -> T, fallback: suspend()): T {
        LoggerFactory.getLogger(javaClass.name).info("Time limiter $commandKey = ${timeLimiterRegistry.timeLimiter(commandKey).timeLimiterConfig.timeoutDuration}")
        val timeLimitedBlock = timeLimiterRegistry.timeLimiter(commandKey).decorateSuspendFunction(block)

        val circuitBreakingTimeLimitedBlock = circuitBreakerRegistry
            .circuitBreaker(commandKey)
            .decorateSuspendFunction(timeLimitedBlock)

        //Use fallback method wherever is necessary in order to be triggered

        return circuitBreakingTimeLimitedBlock()
    }

    companion object {
        const val COMMAND_1 = "command1",
        const val COMMAND_2 = "command2"
    }
}
```
Is this possible?
