### ISSUE TITLE
Circuit Breaker Opens Early

### ISSUE THREAD

**Issue by upen4a3** [resilience4j/resilience4j#1553]
Resilience4j version:
"1.7.0"

Java version:
11

Below are my Resilience4j properties

```
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 6
        sliding-window-type: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions: java.net.Socketexception
```

 
Circuit Breaker is opened after I send one success call and 5 failure calls .Is this correct behavior?

To Test Half Open:I sent 2 successful and 3 failure then Circuit Breaker Opened again.Is this correct behavior?

Could you give some explanation here how slidingWindowSize effecting Circuit Breaker States here.
