### ISSUE TITLE
CircuitBreaker aop is not invoking the fallback

### ISSUE THREAD

**Issue by ilbe-octo** [resilience4j/resilience4j#1572]
Resilience4j version: 1.7.1

Java version: 17

I'm working on a migration strategy from Hystrix to Resilience4j for our microservices.
I've built some mss for testing purposes but apparently, r4j's AOP is not working.

```java
@FeignClient("ext-service")
public interface SomeClient {
  @GetMapping(value = "/{id}")
  List<Model> get(@PathVariable Long id);
}
```

```java
//...
public class ServiceImpl implements Service {
  //...
  private final CircuitBreakerRegistry circuitBreakerRegistry;

  @CircuitBreaker(name = "mService", fallbackMethod = "defaultFallback")
  public Model doSmth(final Model model) {
    log.info("Default CB size {}", circuitBreakerRegistry.getDefaultConfig().getSlidingWindowSize()); // 5
    circuitBreakerRegistry.getAllCircuitBreakers().forEach(c -> {
      log.info("CB name:: {}", c.getName()); // mService
      log.info("CB size:: {}", c.getCircuitBreakerConfig().getSlidingWindowSize()); // 5
    });

    //...
  }

  public Model defaultFallback(final Model model, RuntimeException e) {
   //...
  }

}
```

```yml
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true

feign:
  circuitbreaker:
    enabled: false

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    mService:
      baseConfig: default
```

```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.5.6</version>
    <relativePath />
  </parent>
<properties>
    <java.version>17</java.version>
    <spring-cloud.version>2020.0.4</spring-cloud.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-spring-boot2</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-spring-cloud2</artifactId>
    </dependency>
  </dependencies>
```
