### ISSUE TITLE
CircuitBreaker Overrides Http Message as 500 Internal Error 

### ISSUE THREAD

**Issue by marchest** [resilience4j/resilience4j#1612]
Resilience4j version:
resilience4j-circuitbreaker : 1.7.0
spring-cloud-circuitbreaker-resilience4j : 2.0.2

Java version: openjdk 11.0.13

I am using resiliency in spring cloud gateway project. And I would like to record some specific Http Codes as failure. Hence, I added below config to my route
     
      filters:
            - name: CircuitBreaker
              args:
                name: MY_CIRCUIT_BREAKER
                statusCodes:
                  - 401
                  - 409

```
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      slowCallDurationThreshold: 300ms
      slowCallRateThreshold: 50
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    MY_CIRCUIT_BREAKER:
      baseConfig: default
```

Within above configuration my circuit breaker works well I mean it can count failures based on http status that i specied under route config. But its swallow actual message and returns HTTP 500. Detailed log is below.

`recorded an error: 'org.springframework.cloud.gateway.filter.factory.SpringCloudCircuitBreakerFilterFactory$CircuitBreakerStatusCodeException: 409 CONFLICT'. Elapsed time: 131 ms 2022-01-17T11:55:53.191782442Z 2022-01-17 14:55:53.190 ERROR 7 --- [or-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [54b3d2d3-2] 500 Server Error for HTTP PUT "/bookservice/api/v1/books/741180f5-a32d-40c3-830e-05fc701c1b07" 2022-01-17T11:55:53.191812771Z 2022-01-17T11:55:53.191815233Z org.springframework.cloud.gateway.filter.factory.SpringCloudCircuitBreakerFilterFactory$CircuitBreakerStatusCodeException: 409 CONFLICT 2022-01-17T11:55:53.191817141Z at org.springframework.cloud.gateway.filter.factory.SpringCloudCircuitBreakerFilterFactory$1.lambda$filter$0(SpringCloudCircuitBreakerFilterFactory.java:101) ~[spring-cloud-gateway-server-3.0.4.jar!/:3.0.4] 2022-01-17T11:55:53.191819403Z Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 2022-01-17T11:55:53.191821132Z Error has been observed at the following site(s): 2022-01-17T11:55:53.191822829Z |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] 2022-01-17T11:55:53.191825077Z |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] 2022-01-17T11:55:53.191826936Z |_ checkpoint ⇢ HTTP PUT "/bookservice/api/v1/books/741180f5-a32d-40c3-830e-05fc701c1b07" [ExceptionHandlingWebHandler]`

So, actual message was HTTP 409 and it has some user specific error message. Since the circuit breaker swallow it I only see HTTP 500 at the client side. I was planning to see actual message even if request is interrupted by Circuit breaker.

How to change this behaviour?
