### ISSUE TITLE
No effect on customized configuration about Circuit breaker Spring yaml  

### ISSUE THREAD

**Issue by ryougiitachi-hm** [resilience4j/resilience4j#1635]
Resilience4j version: 1.7.0
Java version: 1.8

Dear Team

I have been studying resilience4j recently. 
When I tried to integrate resilience4j with spring-boot, I found that configurations in applicaiton.yml had no effect. 
Here is my configuration about application.yaml

```yaml
resilience4j.circuitbreaker:
    redis-mock:
      registerHealthIndicator: true
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 2
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 50ms

```
Here is the testing code that is used to test slow call. 
```java
@CircuitBreaker(name = "redis-mock", fallbackMethod = "loadUserInfoFallback")
@Override
public UserDto loadUserInfo(String username) {
    log.info("Start loading user info for username {}.", username);
    try {
        TimeUnit.SECONDS.sleep(1L);
        throw new RuntimeException();
    }
    catch (InterruptedException e) {
        log.error("Thread {} was interrupted. ", Thread.currentThread());
        return UserDto.builder().username(null).build();
    }
}

```
I found slow call didn't have any effect. 

When looking up the source code of io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect from resilience4j-spring-1.7.0, the following code is found: 

```java
private io.github.resilience4j.circuitbreaker.CircuitBreaker getOrCreateCircuitBreaker(
    String methodName, String backend) {
    io.github.resilience4j.circuitbreaker.CircuitBreaker circuitBreaker = circuitBreakerRegistry
        .circuitBreaker(backend);

    if (logger.isDebugEnabled()) {
        logger.debug(
            "Created or retrieved circuit breaker '{}' with failure rate '{}' for method: '{}'",
            backend, circuitBreaker.getCircuitBreakerConfig().getFailureRateThreshold(),
            methodName);
    }

    return circuitBreaker;
}

```
Questions: 
Why is circuit breaker created using the default config rather than customized config in yaml?
Is there any error on my configuration in application.yaml?

Appreciated if kindly help these question ^_^
