### ISSUE TITLE
Circuitbreaker fallback is triggered even when the circuit is closed

### ISSUE THREAD

**Issue by omerk706** [resilience4j/resilience4j#1666]
Resilience4j version: 1.7.1

Java version: 11

In a spring-boot reactor project I have a method annotated with retry and circuitbreaker, and fallbacks defined:
```java
    @CircuitBreaker(name = "es", fallbackMethod = "fallbackCircuitOpen")
    @Retry(name = "es", fallbackMethod = "fallback")
    public Flux<SearchHit> runSearch(SearchRequest request) {
        return reactiveElasticsearchClient.search(request);
    }


    private Flux<SearchHit> fallback(SearchRequest request, ReadTimeoutException throwable) {
        tracer.activeSpan().log("ES Search timed out for request " + request + " with exception: " + throwable);
        return Flux.error(ESNotAvailableException.ofRetriesExceeded("ES Search retries exceeded for request " + request, throwable));
    }

    private Flux<SearchHit> fallback(SearchRequest request, io.netty.channel.ChannelException throwable) {
        tracer.activeSpan().log("ES Search failed for request " + request + " with exception: " + throwable);
        return Flux.error(ESNotAvailableException.ofRetriesExceeded("ES Search retries exceeded for request " + request, throwable));
    }

    private Flux<SearchHit> fallbackCircuitOpen(SearchRequest request, RuntimeException throwable) {
        tracer.activeSpan().log("ES Search failed for request " + request + " with exception: " + throwable);
        return Flux.error(ESNotAvailableException.ofCircuitOpen("ES Search not attempted for request " + request, throwable));
    }
```
    
The configuration is this:
```yml
resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 2
  configs:
    default:
      slidingWindowSize: 100
      registerHealthIndicator: true
  instances:
    es:
      baseConfig: default
      ignoreExceptions:
        - com.ebay.seo.linking.service.exception.ESNotAvailableException
      slidingWindowType: COUNT_BASED
      writable-stack-trace-enabled: true
      automatic-transition-from-open-to-half-open-enabled: true
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 5s
      failureRateThreshold: 100
      minimumNumberOfCalls: 20
resilience4j.retry:
  retryAspectOrder: 1
  configs:
    default:
      maxAttempts: 3
      waitDuration: 10ms
      enableExponentialBackoff: false
      retryExceptions:
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    es:
      baseConfig: default
      retryExceptions:
        - java.util.concurrent.TimeoutException
        - io.netty.channel.ChannelException
        - io.netty.handler.timeout.ReadTimeoutException
        - java.io.IOException
      ignoreExceptions:
        - com.ebay.seo.linking.service.exception.ESNotAvailableException
```

I have a springboot test class:
```java
@Tag("context")
@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = {
        ContextTestConfiguration.class
})
public class ElasticSearchContextTests {

    @Autowired
    ElasticSearchService elasticSearchService;

    @MockBean
    ReactiveElasticsearchClient reactiveElasticsearchClient;


    @Test
    void shouldRetry() {
      given(reactiveElasticsearchClient.search(any(SearchRequest.class))).willReturn(Flux.error(ReadTimeoutException.INSTANCE))
                .willReturn(Flux.just(new SearchHit(12)));

        elasticSearchService.runSearch(new SearchRequest())
                .as(StepVerifier::create)
                .expectErrorMatches(this::verifyESException)
                .verify();

        var esRetry = getCurrentCount(FAILED_WITH_RETRY, "es");
        assertThat(esRetry).isEqualTo(1.0f);
    }
```

The problem is that during the test, despite the circuit being closed (verified by debugger) the fallbackCircuitOpen method is invoked, and no event is registered in the retry metrics, and the fallback retry isn't invoked.

Trying that with version 1.6.1 does invoke the retry fallback, but there is some compatibility issue, and I can't downgrade reactor version.

Also, please add some guides how to verify this works in tests, I had to debug into the aspects to see why my events are not triggered.
And also, please add guides, and examples of how to register a fallback and how to trigger these mechanisms in test for reactor project:
```java
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("name");
Mono.fromCallable(backendService::doSomething)
    .transformDeferred(CircuitBreakerOperator.of(circuitBreaker))
```
