### ISSUE TITLE
Using schedulers in Retry + TimeLimiter

### ISSUE THREAD

**Issue by pprazak** [resilience4j/resilience4j#1709]
Resilience4j version: 1.7.0
Java version: 11

What is good practise when providing the schedulers in Retry or TimeLimiter? I mean, is it good approach to create different schedulers for each stage like this for production? 
```
Decorators.ofSupplier(supplier)
        .withThreadPoolBulkhead(threadPoolBulkheadRegistry.bulkhead(BACKEND))
        .withTimeLimiter(timeLimiterRegistry.timeLimiter(BACKEND), Executors.newSingleThreadScheduledExecutor())
        .withRetry(retryRegistry.retry(BACKEND), Executors.newSingleThreadScheduledExecutor())
        .get().toCompletableFuture().join();
```
When annotations are used I don't have to provide any schedulers. So I wonder what the library itself is doing internally and how would I have to change my code to use the same?

**Comment by RobWin** [comment]
Hi,
you are using Spring Boot, correct? But you can't use annotations.

If you use Spring Boot, you can inject the same `ContextAwareScheduledThreadPoolExecutor` instance which is used by our RetryAspect and TimeLimiterAspect. 

The ContextAwareScheduledThreadPoolExecutor can also be configured externally. Which is necessary if you need context propagators:

```
resilience4j.scheduled.executor:
  corePoolSize: 10
  contextPropagators:
    - io.github.resilience4j.test.TestContextPropagators.TestThreadLocalContextPropagatorWithHolder
```

See: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/retry/configure/RetryAspect.java#L87
