### ISSUE TITLE
I want to set 0 to maxWaitDurationInHalfOpenState

### ISSUE THREAD

**Issue by uc4w6c** [resilience4j/resilience4j#1786]
Resilience4j version: 1.7.1 (and 2.0)

Java version: 17

I use resilience4j-spring-boot2.
I want to declaratively set maxWaitDurationInHalfOpenState to the default value of 0ms. (https://resilience4j.readme.io/docs/circuitbreaker says her default value is 0 [ms])

But when I set it to 0ms, I get the following error:

```
    Property: resilience4j.circuitbreaker.instances.backenda.max-wait-duration-in-half-open-state
    Value: "0ms"
    Origin: class path resource [application.yml] - 11:39
    Reason: java.lang.IllegalArgumentException: maxWaitDurationInHalfOpenState must be greater than or equal to 1 ms.
```

application.yml (example)

```
resilience4j.circuitbreaker:
  instances:
    backendA:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 3
      minimumNumberOfCalls: 1
      permittedNumberOfCallsInHalfOpenState: 3
      maxWaitDurationInHalfOpenState: 0ms
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
```

I'd like to submit a pull request that accepts 0ms if you'd like to fix it.
