### ISSUE TITLE
Spring Boot customizers are not applied without existing config entry

### ISSUE THREAD

**Issue by gavlyukovskiy** [resilience4j/resilience4j#1787]
Resilience4j version: 1.7.1

Java version: 17.0.1.12.1-amzn

Spring Boot version: 2.6.8

Whenever the customizer is used (`CircuitBreakerConfigCustomizer`, `RetryConfigCustomizer`, etc.) without entry in the config, it will not be applied to config.

I'll be using `CircuitBreaker` as an example, but all of them behave in the same way:
```kotlin
@Bean
fun myServiceCircuitBreakerConfigCustomizer(): CircuitBreakerConfigCustomizer =
    CircuitBreakerConfigCustomizer.of("my-service") {
        it.ignoreException { e -> e is ApiException && e.code in 400..499 }
    }
```

If relevant configuration property is created
```
resilience4j:
  circuitbreaker:
    instances:
      my-service:
        slow-call-duration-threshold: 500ms
```
it starts to work.

I assume it's because customizers are only touched during iterating over `instances` and `configs` properties in `CircuitBreakerConfiguration. It looks like it can be fixed by iterating over all remaining customizers and creating default configs for them, but I'm not sure if that would not break something else.

**Comment by RobWin** [comment]
Hi,

would you like to create a PR?
I don't think that it would break something.

**Comment by gavlyukovskiy** [comment]
@RobWin I will do that 👍 Can you please guide me through difference between `config` and `instance`? 
In case customizer is present, but neither `resilience4j.circuitbreaker.instances.<name>` nor `resilience4j.circuitbreaker.configs.<name>` is, should I create default config from customizer in `createCircuitBreakerRegistry` or do it after iterating over instances in `initCircuitBreakerRegistry`?

**Comment by RobWin** [comment]
Hi,

configs can be used to define configurations which can be used by multiple instances and even overwritten:

```
resilience4j.circuitbreaker:
  configs:
    sharedConfig:
      slidingWindowSize: 100
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10s
    backendSharedA:
      baseConfig: sharedConfig
      slidingWindowSize: 6
    backendSharedB:
      baseConfig: sharedConfig
      slidingWindowType: TIME_BASED
```

Right now it's not possible it's not possible to reference a shared config by using a `CircuitBreakerConfigCustomizer`.

In your PR you want to process a CircuitBreakerConfigCustomizer, even if there is no `resilience4j.circuitbreaker.instances.<name`.
