### ISSUE TITLE
Configure the ignore exceptions lambda using circuit breaker config properties

### ISSUE THREAD

**Issue by ceremo** [resilience4j/resilience4j#1885]
Using Spring boot with Circuit-breaker, the configuration can be defined using properties under the namespace `resilience4j.circuitbreaker`, but the ignore exceptions lambda cannot be defined using them, it will be great to create a new property (like `ignoreExceptionsPredicateClass`) to allow to define ignore exceptions with a custom predicate using properties. 
The new property should allow a list of classes implemeting the `Predicate<Throwable>`, for example:
```
resilience4j.circuitbreaker:
    instances:
        backendA:
            registerHealthIndicator: true
            slidingWindowSize: 100
            ...
            ignoreExceptionsPredicateClass:
                - mypackage.MyPredicateClass1
                - mypackage.MyPredicateClass2
```

Regards.
