### ISSUE TITLE
Loosing MDC correlationId when retring

### ISSUE THREAD

**Issue by jimartinmoreno** [resilience4j/resilience4j#1900]
Resilience4j version: 2.0.2

Java version: 17

Good morning, 

We are facing an issue when executing retries on a **Feign** or **Spring reactive WebClient** HTTP client. We are setting the correlationId in the headers of the HTTP request (using an interceptor with Feign or  a filter with Spring reactive WebClient), and everything works fine (we get the correlationId from the SLF4J's MDC, but when the retry mechanism executes retry calls, because the retries are executing different threads we are losing the MDC context.

**Comment by jimartinmoreno** [comment]
We have implemented the following Context propagator: 

```
package com.example.api.config.resilence4j;

import io.github.resilience4j.core.ContextPropagator;
import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.slf4j.MDC;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Component;

import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Supplier;

@Slf4j
@Component
public class CustomContextPropagator implements ContextPropagator<Map<String, String>> {

    @NotNull
    @Override
    public Supplier<Optional<Map<String, String>>> retrieve() {
        return () -> {
            Optional<User> user = getUser();
            log.info("retrieve - user: {}",user);
            log.info("retrieve - mdcContext: {}", MDC.getCopyOfContextMap());

            return Optional.ofNullable(MDC.getCopyOfContextMap());
        };
    }

    @NotNull
    @Override
    public Consumer<Optional<Map<String, String>>> copy() {
        return (copyOfContextMap) -> {
            Optional<User> user = getUser();
            log.info("copy - user: {}",user);
            log.info("copy - mdcContext: {}", MDC.getCopyOfContextMap());

            copyOfContextMap.ifPresent(MDC::setContextMap);
        };
    }

    @NotNull
    @Override
    public Consumer<Optional<Map<String, String>>> clear() {
        return (contextMap) -> {
            Optional<User> user = getUser();
            log.info("copy - user: {}",user);
            log.info("clear - mdcContext: {}", MDC.getCopyOfContextMap());
            MDC.clear();
        };
    }

    @NotNull
    private static Optional<User> getUser() {
        Optional<User> user = Optional.ofNullable(SecurityContextHolder.getContext())
                .map(SecurityContext::getAuthentication)
                .map(authentication -> (User) authentication.getPrincipal());
        return user;
    }
}
```

And we have the following configuration:
```
resilience4j:
  scheduled:
    executor:
      corePoolSize: 10
      contextPropagators:
        - com.example.api.config.resilence4j.CustomContextPropagator

resilience4j.retry:
  retryAspectOrder: 2
  metrics:
    enabled: true
  configs:
    default:
      max-attempts: 3
      waitDuration: 10
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - feign.RetryableException
        - java.net.SocketTimeoutException
        - java.util.concurrent.CompletionException
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - feign.FeignException.InternalServerError
        - feign.FeignException.BadGateway
        - feign.FeignException.ServiceUnavailable
        - feign.FeignException.GatewayTimeout
        - feign.FeignException.FeignServerException
        - org.apache.hc.client5.http.ConnectTimeoutException
        - org.apache.hc.client5.http.HttpHostConnectException
        - com.example.api.exception.FeignErrorDecoder.CustomRetryableException
    defaultHttp:
      maxAttempts: 3
      waitDuration: 10
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.net.ConnectException
        - java.util.concurrent.TimeoutException
        - io.netty.handler.timeout.ReadTimeoutException
        - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
        - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
        - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
        - org.springframework.web.reactive.function.client.WebClientResponseException.TooManyRequests
        - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
        - org.springframework.web.reactive.function.client.WebClientRequestException
  instances:
    unstableService:
      baseConfig: default
    unstableServiceSync:
      baseConfig: default
    unstableServiceHttp:
      baseConfig: defaultHttp
    unstableServiceHttpSync:
      baseConfig: defaultHttp
```

Our CustomContextPropagator is executed but MDC context is always empty.  @RobWin Do we need any additional configuration or implementation? 

Thank you
