### ISSUE TITLE
Unexpected behavior with a record result predicate on a Kotlin suspending method annotated with @CircuitBreaker

### ISSUE THREAD

**Issue by manuarlin** [resilience4j/resilience4j#1957]
Resilience4j version: 2.0.2

Java version: 17
Kotlin version: 1.8.21

Hello,

I tried to add a circuit breaker with a record result predicate on a Kotlin suspending method:
```kotlin
@CircuitBreaker(name = "myCircuitBreaker")
    suspend fun suspendingFoo(shouldFail: Boolean): String {
        someSuspendingFunction()
        return if (shouldFail) FAILURE_VALUE else SUCCESS_VALUE
    }
```
defined with :
```yaml
resilience4j.circuitbreaker:
  instances:
    myCircuitBreaker:
      slidingWindowSize: 2
      minimum-number-of-calls: 1
      failureRateThreshold: 50
      recordResultPredicate: com.example.coroutinecircuitbreakerexample.RecordResultPredicate
```
and the record result predicate being:
```kotlin
class RecordResultPredicate : Predicate<Any> {

    private val logger: Logger = LoggerFactory.getLogger(RecordResultPredicate::class.java)

    override fun test(result: Any): Boolean {
        logger.info("Calling result predicate with result of type ${result.javaClass}")
        return result is String && result == FAILURE_VALUE
    }
}
```
I was expecting the circuit breaker to have the OPEN state after forcing some failure but it was still in CLOSED state. I tried to remove the suspending part and it worked perfectly.
I also tried to define programmatically the circuit breaker and not using the `@CircuitBreaker` annotation and I got the expected behavior too.

An example to reproduce the problem is available here: https://github.com/manuarlin/coroutine-circuitbreaker-example. The two integration tests `DemoWithAnnotationTests` and `DemoWithoutAnnotationTests` are here to test each case.

Finally I noticed that the type of the parameter of my record result predicate was not a String as expected but a `kotlin.coroutines.intrinsics.CoroutineSingletons` instead.

Thanks for any attention to this issue ❤️.
