### ISSUE TITLE
resilience4j-spring-cloud2 doesn't update config

### ISSUE THREAD

**Issue by yuna878** [resilience4j/resilience4j#1960]
Resilience4j version: 2.0.2

Java version: 17

Hello, I am using resilience4j-spring-boot2 for @CircuitBreaker annotations and also added resilience4j-spring-cloud2 to get support for runtime config updates.
I have a spring-cloud-config server embedded within the same application ( server == client).
Through `http://localhost:8080/actuator/env`, I can check that spring cloud config is correctly reading the new configs when configs get updated at runtime.
However, the circuit breaker configs don't seem to get updated.

Please take a look. If you need any additional information, please let me know.

# Dependencies
```
ext {
    springBootVersion = "2.7.12"
    mongoDriverVersion = "4.7.2"
    lombokVersion = "1.18.26"
    springCloudVersion = "4.0.2"
    resilience4jVersion = "2.0.2"
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.mongodb:mongodb-driver-sync:$mongoDriverVersion"
    implementation "org.mongodb:mongodb-driver-core:$mongoDriverVersion"
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'org.apache.commons:commons-lang3:3.0'
    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    implementation 'net.logstash.logback:logstash-logback-encoder:7.2'
    implementation "io.github.resilience4j:resilience4j-spring-boot2:$resilience4jVersion"
    implementation "io.github.resilience4j:resilience4j-spring-cloud2:$resilience4jVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-aop:$springBootVersion"
    implementation "org.springframework.cloud:spring-cloud-config-server:$springCloudVersion"
    implementation "org.springframework.cloud:spring-cloud-starter-bootstrap:$springCloudVersion"
}
```

# Application.yaml
```
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      failureRateThreshold: 60
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      permittedNumberOfCallsInHalfOpenState: 4
      maxWaitDurationInHalfOpenState: 1000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10000
```

# config.yaml hosted by spring-cloud-config
```
resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 80 #modify value at runtime and POST to /actuator/refresh
```

# Controller
```
@Slf4j
@RestController
@RequestMapping("/resilience4j")
@RefreshScope
public class Resilience4JController {
    @Autowired
    Resilience4JService resilience4JService;
    @Autowired
    CircuitBreakerRegistry circuitBreakerRegistry;
    @Autowired
    Environment environment;

    @GetMapping("/test")
    public String greeting() {
        return resilience4JService.hello();
    }

    @GetMapping("/value")
    public String getValue() {
        return environment.getProperty("test.value");
    }

    @GetMapping("/config")
    public String getConfig(@RequestParam String name) {
        return circuitBreakerRegistry.getDefaultConfig().toString();
    }
}
```

# result: /resilience4j/config
```
CircuitBreakerConfig {recordExceptionPredicate=io.github.resilience4j.circuitbreaker.CircuitBreakerConfig$$Lambda$1097/0x00000008016d1fe0@264aa596, ignoreExceptionPredicate=io.github.resilience4j.circuitbreaker.CircuitBreakerConfig$$Lambda$1098/0x00000008016d2230@33cf71e9, recordExceptions=[], ignoreExceptions=[], failureRateThreshold=80.0, permittedNumberOfCallsInHalfOpenState=4, slidingWindowSize=10, slidingWindowType=COUNT_BASED, minimumNumberOfCalls=10, writableStackTraceEnabled=true, automaticTransitionFromOpenToHalfOpenEnabled=false, waitIntervalFunctionInOpenState=io.github.resilience4j.core.IntervalFunction$$Lambda$1102/0x00000008016d3380@287a881d, slowCallRateThreshold=100.0, slowCallDurationThreshold=PT1M}
```

# when POST to /actuator/refresh
```
[
    "resilience4j.circuitbreaker.configs.default.failureRateThreshold"
]
```
