### ISSUE TITLE
ignoreExceptions & recordExceptions not work in resilience4j-spring-boot3 v2.0.2

### ISSUE THREAD

**Issue by paulbors** [resilience4j/resilience4j#2026]
Resilience4j version: 2.0.2

Java version: 17

I am using below artifacts w/ Spring Boot 3.x
```xml
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot3</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-reactor</artifactId>
            <version>2.0.2</version>
        </dependency>
```

With below configuration:
```properties
resilience4j.circuitbreaker.configs.default.registerHealthIndicator = true
resilience4j.circuitbreaker.configs.default.slidingWindowSize = 10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls = 5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState = 3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled = true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState = 5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold = 50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize = 10

resilience4j.circuitbreaker.instances.randomActivity.ignore-exceptions[0] = jorg.springframework.web.reactive.function.client.WebClientException
```

However, the annotation based circuit breaker below is still falling back:
```Java
    @GetMapping
    @CircuitBreaker(name = "randomActivity", fallbackMethod = "fallbackRandomActivity")
    @Bulkhead(name = "randomActivity")
    public String getRandomActivity() {
        ResponseEntity<Activity> responseEntity = restTemplate.getForEntity(BORED_API, Activity.class);
        Activity activity = responseEntity.getBody();
        log.info("Activity received: " + activity.getActivity());
        return activity.getActivity();
    }
```

Any help / hint is appreciated!

**Comment by RobWin** [comment]
Hi, fallback mechnism is just like a try/catch.
Ignore exceptions has nothing to do with the fallback mechnism, but just controls if the CircuitBreaker should count it as a failure or not.

**Comment by larrynikx** [comment]
Hi, coming from hystrix this was confusing for me as well. Expected the ignored exceptions not to trigger the fallback.

Ended up implementing it as follows:
```
public interface BaseFeignClientFallbackFactory<F> extends FallbackFactory<F> {

	@Override
	default F create(Throwable cause) {
		if (cause instanceof IgnorableException ex)
			throw ex;
		return createFallback(cause);
	}

	F createFallback(Throwable cause);
}
```

In your error decoder add some logic to detect & return/throw the exception you want to ignore
Your feign clients can then have fallbacks that implement this interface.

**Comment by koidearepos** [comment]
Hi, I added circuit breaker configuration like that. And I added it in Spring Cloud Gateway. Circuit breaker works for slow request but it doesn't work for failed request. I logged and log says request is successful so circuit breaker cannot count all of them. How can i fix it? 

```
resilience4j:
  circuitbreaker:
    configs:
      defaultCircuitbreaker:
        slidingWindowType: COUNT_BASED #Kayıt altına alınan data kıstası. Saniye olarakta belirlenebilmektedir.
        slidingWindowSize: 10 #Son x datanın dikkate alınmasını sağlar.
        minimumNumberOfCalls: 5 #Asgari kayıt sayısını belirler. Bu kayıt sayısından sonra algoritmalar çalışacaktır.
        permittedNumberOfCallsInHalfOpenState: 2 #Sigora yarı açıkken yapılacak max kayıt sayısı.
        automaticTransitionFromOpenToHalfOpenEnabled: true #Sigortanın açık konumdan yarı-açık konuma gelmesini üsrecinin atomatize edilmesi sağlar.
        failureRateThreshold: 50 #% cinsinden ne kadar bir fail oranı olursa sigorta açık konuma gelecek bilgisi girilir.
        waitDurationInOpenState: 60s #Açık olan devre saniye sonra yarı açık hal gelecektir.
        slowCallDurationThreshold: 30s #Saniye üzerinde dönen request'leri yavaş olarak kabul edecektir.
        slowCallRateThreshold: 90 #Yavaş request sayısı %x'i aşarsa sigorta yarı-açık konuma gelecektir.
        registerHealthIndicator: true
    instances:
      fallbackAuth:
        baseConfig: defaultCircuitbreaker
      fallbackUser:
        baseConfig: defaultCircuitbreaker
      fallbackEvent:
        baseConfig: defaultCircuitbreaker
      fallbackComment:
        baseConfig: defaultCircuitbreaker
      fallbackParticipant:
        baseConfig: defaultCircuitbreaker
  timelimiter:
    configs:
      defaultTimelimiter:
        timeoutDuration: 20s
    instances:
      fallbackAuth:
        baseConfig: defaultTimelimiter
      fallbackUser:
        baseConfig: defaultTimelimiter
      fallbackEvent:
        baseConfig: defaultTimelimiter
      fallbackComment:
        baseConfig: defaultTimelimiter
      fallbackParticipant:
        baseConfig: defaultTimelimiter
```
