### ISSUE TITLE
Exception Thrown creating CircuitBreakerRegistry default bean in version 2.1.0

### ISSUE THREAD

**Issue by thejeff77** [resilience4j/resilience4j#2036]
Resilience4j version: 2.1.0

Java version: 11

Thanks for raising a Resilience4j issue.

Hey team, when bumping Resilience4j up to 2.1.0 from 2.0.2, and Spring from 3.0.3 to 3.1.5, I'm seeing a weird exception - Resilience4j can no longer create the CircuitBreakerRegistry default bean. This exception occurs when trying to create it:

```
Factory method 'circuitBreakerRegistry' threw exception with message: 'java.util.Optional io.github.resilience4j.core.predicate.PredicateCreator.createExceptionsPredicate(java.util.function.Predicate, java.lang.Class[])'
```

Here is my application.yaml configuration:
```
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 40
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 30
        slowCallDurationThreshold: 10000
        failureRateThreshold: 80
    instances:
      mmpServiceCB:
        baseConfig: default
      famServiceCB:
        baseConfig: default
      ecsServiceCB:
        baseConfig: default
```

I've search all over online, and checked the issues list, and haven't been able to find anything out.

Thanks for any help!
