### ISSUE TITLE
TimeLimiter configuration (and maybe CircutBreakerConfiguration) seem to be ignored when using e.g. FeignClients

### ISSUE THREAD

**Issue by oliverfuehrer** [resilience4j/resilience4j#2062]
Resilience4j version:  spring-cloud-circuitbreaker-resilience4j-3.1.0-RC1.jar
Java version: openjdk version "21.0.1" 2023-10-17

I wrote a spring boot test  program for different rest frameworks: RestClient, WebClient and OpenFeign:
see https://github.com/oliverfuehrer/restdemo

I tried to test CircutBreaker behaviour within feign client controller. I wanted to configure TimeLimiter timeout to something different then default value (1s), but I always get the default. See following configuration:

```
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
resilience4j:
  circuitbreaker:
    instances:
      RestserverDemoFeignClientgetSampleResponse:
        minimumNumberOfCalls: 5
  timelimiter:
    instances:
      RestserverDemoFeignClientgetSampleResponse:
        timeoutDuration: 20s
```

The problem could be that within spring-cloud-circuitbreaker-resilience4j-3.1.0-RC1-sources.jar!/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerFactory.java:165 only the defaultConfiguration is used 'this.circuitBreakerRegistry.getConfiguration(id)' but the correct TimeLimiterConfiguration is stored within the entryMap of the used Registry.
See attached screenshot from my debug session:

![image](https://github.com/resilience4j/resilience4j/assets/10271518/e3f2b433-a643-4806-97df-15f41f44eec4)
