### ISSUE TITLE
ThreadPoolBulkhead rejects tasks when using queue and threads are kept alive

### ISSUE THREAD

**Issue by molikuner** [resilience4j/resilience4j#2125]
# Environment
* Resilience4j version: `2.1.0` and `2.2.0`
* Java version: `openjdk version "21.0.2" 2024-01-16 LTS`
* Module: Bulkhead

# Problem

While running a spring boot application with resilience4j-bulkhead we found some strange behavior where the ThreadPoolBulkhead rejects some tasks for no apparent reason. Additionally we noticed that the thread pool never shrinks (in the reproducer I could verify that threads are being replaced after waiting idly, but I couldn't verify this in production yet due to limited debugging possibilities).

# Reproducer

The reproducer will schedule 4 tasks every 2 seconds. Each task will take one second. The thread pool will have a maximum size of 5 threads. After a few iterations some tasks are getting rejected even though the thread pool should have enough capacity to work on the tasks. Unfortunately this isn't as consistent as I would like it to be and varies from run to run, but using the setup shown below I see first failures in the third iteration. Nevertheless sometimes if just fails as late as the sixth iteration.

## Source

```kotlin
import io.github.resilience4j.bulkhead.BulkheadFullException
import io.github.resilience4j.bulkhead.ThreadPoolBulkheadConfig
import io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry
import java.time.Duration

fun main() {
    val config = ThreadPoolBulkheadConfig.custom()
        .maxThreadPoolSize(5)
        .coreThreadPoolSize(1)
        .queueCapacity(1)
        .keepAliveDuration(Duration.ofSeconds(5))
        .build()

    val registry = ThreadPoolBulkheadRegistry.of(config)

    val bulkhead = registry.bulkhead("worker")

    var i = 0
    while (true) {
        println("loop $i: scheduling 4 tasks")
        repeat(4) {
            println("$i-$it: scheduling task")
            try {
                bulkhead.executeRunnable {
                    println("$i-$it: starting in ${Thread.currentThread()}")
                    Thread.sleep(Duration.ofSeconds(1))
                    println("$i-$it: finishing in ${Thread.currentThread()}")
                }
            } catch (e: BulkheadFullException) {
                System.err.println("$i-$it: failed to schedule: ${e.message}")
            }
        }
        Thread.sleep(Duration.ofSeconds(2))
        i++
    }
}
```

Please see the attached log where the first task being rejected is `3-1`: [broken.log](https://github.com/resilience4j/resilience4j/files/14480644/broken.log)

## Config causing problems:
```yaml
maxThreadPoolSize: 5
coreThreadPoolSize: 1
queueCapacity: 1
keepAliveDuration: 5000 # 5 seconds
```

# Workaround
It seems tasks can easily start new threads, but re-using an existing threads in combination with a queue causes some kind of overhead leading to rejected tasks.

## Workaround Config 1
While testing I found that this issue doesn't occur when the queue has a capacity of 0:

```yaml
maxThreadPoolSize: 5
coreThreadPoolSize: 1
queueCapacity: 0
keepAliveDuration: 5000 # 5 seconds
```

## Workaround Config 2
Another workaround that I found is, that it seems to be working correctly in case the thread pool shrinks before receiving new tasks and therefore always causing the tasks to start new threads:

```yaml
maxThreadPoolSize: 5
coreThreadPoolSize: 1
queueCapacity: 1
keepAliveDuration: 200 # 200 ms => will shrink the thread pool for 800 ms before the new tasks are received
```

**Side note:** this could impact performance as threads are potentially not being reused
