### ISSUE TITLE
Circuit breaker in DISABLED state sill moving back to HALF_OPEN/OPEN

### ISSUE THREAD

**Issue by jmereaux** [resilience4j/resilience4j#2135]
Resilience4j version: 2.2.0

Java version: 17

After putting a circuit breaker instance to DISABLED state (using the transitionToDisabledState method), it is automatically moving to HALF_OPEN/OPEN when reaching the failure rate threshold.

Is it expected?

Is there any other way to disable a circuit breaker instance programmatically at runtime ?

Thanks 😊

**Comment by RobWin** [comment]
No, this is not expected. Could you please show some logs and code?

**Comment by jmereaux** [comment]
Oh, you're right !

I had not realized I did have multiple instances of the circuit breaker. My app is running on Kubernetes and is spread on 3 pods. So when I send the "disable" request to the CB, actually, I'm only disabling one single instance. The two other ones are still active and can have their state changed.

I guess, I will have to find another solution to globally disable the circuit breaker

**Comment by jmereaux** [comment]
Is there any way to conditionally activate the @CircuitBreaker annotation on my `debitCard` method ?

**Comment by RobWin** [comment]
No, unfortunately not.
You could define a `ignoreExceptionPredicate` and this predicate could ignore any exception when you want the CircuitBreaker to be disabled. 

>A custom Predicate which evaluates if an exception should be ignored and neither count as a failure nor success.

**Comment by RobWin** [comment]
Yes, it would ignore any exception. That means even TimeoutException would not increase the failure rate or the slow call rate.

**Comment by jmereaux** [comment]
@RobWin Would you have any sample explaining how to implement the ignoreExceptionPredicate please ? I could not find anything in the doc.
Thanks

**Comment by RobWin** [comment]
Similar to the failure rate predicate.
Just implement a Java Predicate and configure it in our config file.

**Comment by jmereaux** [comment]
Hi @RobWin 
I've come up to the following implementation :

```
public class CircuitBreakerIgnoreExceptionPredicate implements Predicate<Exception> {

    private static final String MS3_CIRCUITBREAKER_ENABLED_ENV_VAR_NAME = "MS3_CIRCUITBREAKER_ENABLED";

    @Override
    public boolean test(Exception e) {
        var ms3CircuitBreakerEnabled = Boolean.parseBoolean(System.getenv(MS3_CIRCUITBREAKER_ENABLED_ENV_VAR_NAME));
        log.debug("Testing exception {} - CircuitBreaker enabled : {}", e.getClass(), ms3CircuitBreakerEnabled);
        if (ms3CircuitBreakerEnabled) {
            return e instanceof CardDisabledException || e instanceof CardNotFoundException
                    || e instanceof CardThrottlingException || e instanceof RequestNotPermitted;
        }
        return true;
    }
}
```

with the following configuration

```
resilience4j:
  circuitbreaker:
    instances:
      MS3CircuitBreaker:
        registerHealthIndicator: true
        failure-rate-threshold: 100
        ignoreExceptionPredicate: com.test.CircuitBreakerIgnoreExceptionPredicate
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
```

When my env var `MS3_CIRCUITBREAKER_ENABLED` is set to false, the circuit still opens when I send 5 slow requests above the threshold of 2000ms.
I would also like to ignore these slow requests when I disable my CircuitBreaker.

Did I miss anything ? Thanks
