### ISSUE TITLE
circuit breaker not generating failure rate exceeded event at expected interval

### ISSUE THREAD

**Issue by BigMikeATL** [resilience4j/resilience4j#2178]
Resilience4j version: 1.7.1

Java version: 8

I have r4j cb configured such that my expectation is that it will generate a failure rate exceeded event if the threshold of 100% is sustained for 3 minutes (180 seconds). That is not happening. Instead what I am seeing is that I will have some percentage of failures for about 2 minutes, it will jump to 100% sustained failures for about a minute, and then the failure rate exceeded event occurs.

Here is my configuration:
```
      slidingWindowSize: 180                  
      slidingWindowType: TIME_BASED           
      minimumNumberOfCalls: 10               
      failureRateThreshold: 100              
      eventConsumerBufferSize: 10
      recordExceptions:                       
        <recorded>
      ignoreExceptions:                      
        <ignored>
```

Is there an issue with the configuration? do I have a fundamental misunderstanding of the mechanics here? or do we have a bug?

I've attached a screenshot of the corresponding metrics, illustrating the behavior.
<img width="648" alt="Screenshot 2024-06-14 at 3 14 49 PM" src="https://github.com/resilience4j/resilience4j/assets/7064121/dfc72de8-62cd-4772-9695-cc7c7132f0da">
