### ISSUE TITLE
Missing documentation about retryExceptions configuration when building AOT / native image

### ISSUE THREAD

**Issue by danparisi** [resilience4j/resilience4j#2184]
When configuring _resilience4j **reply**_ by adding _retryExceptions_ list like in the example below, if you are supposed to build a native image you also need to provide _GraalVM_ reflection hints. Everything works fine if you do that, but this is not documented anywhere it seems.

Here is the configuration example about the case:
```
resilience4j:
  retry:
    configs:
        retryExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          ...
```

In case you don't add such hints, you will get some runtime error like the following:
```
    Property: resilience4j.retry.configs.default.retry-exceptions[2]
    Value: "java.net.SocketTimeoutException"
    Origin: class path resource [application.yml] - 98:13
    Reason: failed to convert java.lang.String to java.lang.Class<java.lang.Throwable> (caused by java.lang.ClassNotFoundException: java.net.SocketTimeoutException)
```

Here is an example of GraalVM hint that should be added in _reflect-config.json_ to avoid the runtime exception:
```
[
  {
    "name": "java.net.SocketTimeoutException",
    "allPublicMethods": true,
    "allPublicClasses": true,
    "allDeclaredMethods": true,
    "allDeclaredClasses": true,
    "allPublicConstructors": true,
    "allDeclaredConstructors": true
  },
  ...
```
