### ISSUE TITLE
RateLimiter on Micronaut does not throw TooManyRequest 429

### ISSUE THREAD

**Issue by tomgeek27** [resilience4j/resilience4j#2288]
I have a Microanut application with an endpoint annotated with `@RateLimiter` and I'd expect that if a defined threshold of requests in a defined time window is exceeded it should return a 429 http response by default.

Here is my code:

```java
@Controller("/private/v1/eol")
public class EndOfLineController {

  @Post
  @RateLimiter(name = "eol", fallbackMethod = "eolFallback")
  public MutableHttpResponse<?> eol() {
    doSomething();
  }

  @Executable
  public MutableHttpResponse<?> eolFallback(RequestNotPermitted requestNotPermitted) {
    return HttpResponse.status(HttpStatus.TOO_MANY_REQUESTS)
        .body("/eol does not permit further calls. Retry in few seconds.");
  }
}
```

and here my`application.yml`:

```yaml
#...
resilience4j:
  ratelimiter:
    enabled: ${RATE_LIMITER_ENABLED:true}
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: ${RATE_LIMITER_REQUESTS_NUMBER:10}
        limitRefreshPeriod: ${RATE_LIMITER_REFRESH_PERIOD:1s}
        timeout-duration: 0
    instances:
      eol:
        baseConfig: default
```

I managed it in this way but the problem comes when `doSomething` throws: it seems that RateLimiter catches it and redirect the flow to the fallbackMethod (`eolFallback`). Is it intended? 

So my question is:

- Am I doing something wrong?
- Is there any way to handle 429 by default without a fallback method?
- If my configuration is correct, how can I avoid that every exception go trough the fallbackMethod?

Thanks
