### ISSUE TITLE
Issue with `recordExceptionPredicate` and `ignoreExceptionPredicate` for `WebClientResponseException` variants in Circuit Breaker configuration

### ISSUE THREAD

**Issue by enesoral** [resilience4j/resilience4j#2295]
#### **Description**:
We are facing an issue with the behavior of the `recordExceptionPredicate` and `ignoreExceptionPredicate` in our circuit breaker configuration for `WebClientResponseException` and its subclasses, particularly `BadRequest` and `NotFound`. The issue arises when specific subclasses of `WebClientResponseException`, such as `BadRequest`, are listed under `ignoreExceptions`, which results in conflicting behavior when evaluating exceptions. Specifically, the predicate for `recordExceptionPredicate` returns `true` for exceptions like `WebClientResponseException.BadRequest`, while it should be ignored according to the configuration.

The issue seems to be rooted in how the configuration differentiates between the parent class (`WebClientResponseException`) and its subclasses (`BadRequest`, `NotFound`, etc.), causing an overlap in the `recordExceptionPredicate` and `ignoreExceptionPredicate` behavior.

#### **Circuit Breaker Configuration**:
```yaml
resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      mlPlatformCircuitBreaker:
        waitDurationInOpenState: 300
        slidingWindowSize: 50
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 200
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.net.UnknownHostException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException$NotFound
          - java.net.ConnectException
```

#### **Test Code**:
```java
  private record CircuitBreakerTestConfig(Long waitDurationInOpenState,
                                            Integer slidingWindowSize,
                                            Integer minimumNumberOfCalls,
                                            String slidingWindowType,
                                            Float failureRateThreshold,
                                            Float slowCallRateThreshold,
                                            Long slowCallDurationThreshold,
                                            List<Class<? extends Throwable>> recordExceptions,
                                            List<Class<? extends Throwable>> ignoreExceptions) {}

  private record CircuitBreakerTestParams(String breakerName,
                                          String testUrl,
                                          String successBody,
                                          String className,
                                          String methodName,
                                          Object[] methodArgs,
                                          CircuitBreakerTestConfig testConfig) {}

  private static Stream<Arguments> circuitBreakerTestParams() {
      return Stream.of(
              Arguments.of(new CircuitBreakerTestParams(
                      "mlPlatformCircuitBreaker",
                      "/v2/models/mealpreptimepredictionlgb/versions/1/infer",
                      "{\"outputs\": [{\"data\": [1.23]}]}",
                      "com.trendyol.orange.deliverystoreanalyticsapi.infrastructure.out.rest.mlops.MLOpsAdapter",
                      "getMealPrepTimePrediction",
                      new Object[]{List.of(1.0, 2.0, 3.0)},
                      new CircuitBreakerTestConfig(
                              300L, 50, 5, "COUNT_BASED",
                              50.0f, 50.0f, 200L,
                              List.of(
                                      org.springframework.web.reactive.function.client.WebClientRequestException.class,
                                      org.springframework.web.reactive.function.client.WebClientResponseException.class,
                                      java.util.concurrent.TimeoutException.class,
                                      java.net.UnknownHostException.class,
                                      java.net.ConnectException.class
                              ),
                              List.of(
                                      org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest.class,
                                      org.springframework.web.reactive.function.client.WebClientResponseException.NotFound.class
                              )
                      )
              ))
      );
  }

@ParameterizedTest
@MethodSource("circuitBreakerTestParams")
void should_circuit_breaker_config_set_correct(CircuitBreakerTestParams params) {
    CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker(params.breakerName());
    circuitBreaker.reset();

    long waitDurationMs = circuitBreaker.getCircuitBreakerConfig().getWaitIntervalFunctionInOpenState().apply(1);
    int slidingWindowSize = circuitBreaker.getCircuitBreakerConfig().getSlidingWindowSize();
    String slidingWindowType = circuitBreaker.getCircuitBreakerConfig().getSlidingWindowType().toString();
    float failureRateThreshold = circuitBreaker.getCircuitBreakerConfig().getFailureRateThreshold();
    float slowCallRateThreshold = circuitBreaker.getCircuitBreakerConfig().getSlowCallRateThreshold();
    int minimumNumberOfCalls = circuitBreaker.getCircuitBreakerConfig().getMinimumNumberOfCalls();
    Long slowCallDurationThreshold = circuitBreaker.getCircuitBreakerConfig().getSlowCallDurationThreshold().toMillis();

    assertEquals(params.testConfig().waitDurationInOpenState(), waitDurationMs);
    assertEquals(params.testConfig().slidingWindowSize(), slidingWindowSize);
    assertEquals(params.testConfig().slidingWindowType(), slidingWindowType);
    assertEquals(params.testConfig().failureRateThreshold(), failureRateThreshold);
    assertEquals(params.testConfig().failureRateThreshold(), failureRateThreshold);
    assertEquals(params.testConfig().slowCallRateThreshold(), slowCallRateThreshold);
    assertEquals(params.testConfig().minimumNumberOfCalls(), minimumNumberOfCalls);
    assertEquals(params.testConfig().slowCallDurationThreshold(), slowCallDurationThreshold);

    Predicate<Throwable> recordExceptionPredicate = circuitBreaker.getCircuitBreakerConfig().getRecordExceptionPredicate();
    Predicate<Throwable> ignoreExceptionPredicate = circuitBreaker.getCircuitBreakerConfig().getIgnoreExceptionPredicate();

    List<Class<? extends Throwable>> testExceptions = List.of(
            org.springframework.web.reactive.function.client.WebClientRequestException.class,
            org.springframework.web.reactive.function.client.WebClientResponseException.class,
            org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest.class,
            org.springframework.web.reactive.function.client.WebClientResponseException.NotFound.class,
            java.util.concurrent.TimeoutException.class,
            java.net.UnknownHostException.class,
            java.net.ConnectException.class
    );

    for (Class<? extends Throwable> exceptionClass : testExceptions) {
        Throwable exceptionInstance = createExceptionInstance(exceptionClass);
        boolean isRecorded = recordExceptionPredicate.test(exceptionInstance);
        boolean isIgnored = ignoreExceptionPredicate.test(exceptionInstance);

        if (params.testConfig().ignoreExceptions().contains(exceptionClass)) {
            assertTrue(isIgnored, "Expected exception " + exceptionClass.getSimpleName() + " to be ignored");
            assertFalse(isRecorded, "Expected exception " + exceptionClass.getSimpleName() + " to be ignored");
        } else {
            assertTrue(isRecorded, "Expected exception " + exceptionClass.getSimpleName() + " to be recorded");
            assertFalse(isIgnored, "Expected exception " + exceptionClass.getSimpleName() + " to be recorded");
        }
    }
}
```

When I remove this line of code, the test is passing.
```java 
assertFalse(isRecorded, "Expected exception " + exceptionClass.getSimpleName() + " to be ignored");
```

#### **Observed Issue**:
- **Expected**: When an exception, such as `WebClientResponseException.BadRequest`, is specified under `ignoreExceptions`, it should be ignored by the `ignoreExceptionPredicate` and should not trigger the `recordExceptionPredicate`.
- **Actual**: The `recordExceptionPredicate` returns `true` for `WebClientResponseException.BadRequest` even though it should be ignored. Other exceptions listed under `ignoreExceptions`, such as `java.net.ConnectException`, are correctly ignored.

We use spring boot 3.1.2 and resilience4j 2.0.2
