### ISSUE TITLE
Inconsistent Configuration Parsing When Using Different Registries

### ISSUE THREAD

**Issue by IMSterling** [resilience4j/resilience4j#2319]
Using: 
**io.github.resilience4j:resilience4j-spring-boot3:2.3.0** 
**Spring boot 3.4.37** 

Defining a minimal amount of config in application.yml
```yaml
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 14s
  thread-pool-bulkhead:
    configs:
      default:
        queueCapacity: 2
```
And then can setup a service to showcase the issue

```java
@Service
public class TestService {
    
    public TestService() throws Exception {
        TimeLimiterRegistry timeLimiterRegistry = TimeLimiterRegistry.ofDefaults();
        TimeLimiter tl = timeLimiterRegistry.timeLimiter("test");
        if (Duration.ofSeconds(14).equals(tl.getTimeLimiterConfig().getTimeoutDuration())) {
            throw new Exception("**Fail with tl:" + tl.getTimeLimiterConfig().getTimeoutDuration());
        }

        ThreadPoolBulkheadRegistry registry = ThreadPoolBulkheadRegistry.ofDefaults();
        ThreadPoolBulkhead bulkhead = registry.bulkhead("test");
        ThreadPoolBulkhead.Metrics metrics = bulkhead.getMetrics();
        if (metrics.getRemainingQueueCapacity() != 2) {
            throw new Exception("**Fail with capacity:" + metrics.getRemainingQueueCapacity());
        }
    }
}
```

The default configuration for the timeLimiter is adjusted as expected, but the configuration for the ThreadPoolBulkhead is not. 
* Why is this ? 
* How do I define a default configuration for a threadpoolBulkhead, instantiated via a registry (instead of via annotation) ?
