### ISSUE TITLE
CircuitBreaker configuration groups

### ISSUE THREAD

**Issue by leonard84** [resilience4j/resilience4j#268]
I'd like to be able to define a common configuration for a group of circuit breakers.

Scenario: I have _n_ backends that are independent of each other and should have their own circuit breakers. However, they should have the same config.

It could be configured simliar to the existing [config](https://resilience4j.github.io/resilience4j/#_configuration):
```yaml
resilience4j.circuitbreaker:
    templates:
        group1:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
```

And using it could look like `circuitBreakerRegistry.circuitBreaker("group1", getHost(serviceUrl);` or `circuitBreakerRegistry.circuitBreaker("group1." + getHost(serviceUrl);`

**Comment by storozhukBM** [comment]
Hi @leonard84,
Thank you for you feedback and for using our library.

In general we recomend our users to configure circuit breakers and rate limiters specificaly for each type of backend they are working with. It leads to better system fault tolerance and faster prevention of error propagation in your cluster. Idealy you should use metrics about througput and latency from production cluster for configuration tuning. You can also check this [SO answer](https://stackoverflow.com/questions/48414306/resilience4j-circuit-breaker-ring-bit-buffer-size-configuration/48421333#48421333) about configuration.

Please don't get me wrong, I'm not saying that you're doing something not right. It's just advices based on my experience.

Current configuration properties are designed in such way to be flexible and easy to use for most users. Off course, you can override registry creation in any time and populate it with your own custom shared configurations.
For now, I'm not sure that, such configuration template functionality in the main repository will be beneficial for most of our users?
Maybe there are other library clients that face similar configuration problem?

Hopefully this comment was heplfull. If you have any other questions, comments or other feedback, I'll be happy to help.

**Comment by RobWin** [comment]
It 0.15.0 you will be able to overwrite the default configuration and define base configurations as follows:

```
resilience4j.circuitbreaker:
  configs:
    default:
      ringBufferSizeInClosedState: 100
      ringBufferSizeInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    group1:
      ringBufferSizeInClosedState: 100
      ringBufferSizeInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  backends:
    backendSharedA:
      baseConfig: default
      ringBufferSizeInClosedState: 6
    backendSharedB:
      baseConfig: group1
```
