### ISSUE TITLE
CircuitBreakerRegistry Events, Configuration

### ISSUE THREAD

**Issue by raghanag** [resilience4j/resilience4j#451]
Hi All, Thanks for providing the great library. Could you please clarify the below issues.

1. When I try to use the below code, the getEventPublisher is simply not available as part of the CircuitBreakerRegistry object. May I know what I am missing or doing wrong.

```
circuitBreakerRegistry.getEventPublisher()
            .onEntryAdded(entryAddedEvent -> {
    CircuitBreaker addedCircuitBreaker =  entryAddedEvent.getAddedEntry();
    LOG.info("CircuitBreaker {} added", addedCircuitBreaker.getName());
    addedCircuitBreaker.getEventPublisher().onEvent(circuitBreakerEvent -> LOG.info(circuitBreakerEvent.toString()));
  })
          .onEntryRemoved(entryRemovedEvent -> {
    CircuitBreaker removedCircuitBreaker =  entryRemovedEvent.getRemovedEntry();
    LOG.info("CircuitBreaker {} removed", removedCircuitBreaker.getName());
  });
```
I used the below code to create the circuitbreaker from customconfig and from registry.

```
  CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
          .failureRateThreshold(50)
          .ringBufferSizeInHalfOpenState(2)
          .ringBufferSizeInClosedState(4)
          .build();
  CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

  CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");
```

2. Configuration properties from yaml for spring boot starter library. Shall I assume backendA as the circuitbreaker name that created as part of the code. And the **backends:** is a reserved keyword as part of the yaml where it works as a starting point to find the circuit breaker names and its configurations? And also I dont see the resilience4j properties as part of the spring boot Appendix A, does that meant its not officially supported by the Spring project.

[Common Spring boot properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)

```
resilience4j.circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
        backendB:
            ringBufferSizeInClosedState: 10
            ringBufferSizeInHalfOpenState: 5
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
```
