### ISSUE TITLE
Defaults for Retry similar to Circuit Breaker in spring-boot

### ISSUE THREAD

**Issue by Macarse** [resilience4j/resilience4j#464]
With circuit breakers, I can define a default config and use a `baseConfig` per backend. Example:
```
resilience4j.circuitbreaker:
  configs:
    default:
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10
      failureRateThreshold: 30
      eventConsumerBufferSize: 10
  backends:
    backendA:
      baseConfig: default
```

but I can't do the same thing with Retry and my config looks like this:

```
resilience4j.retry:
  backends:
    backendA:
      maxRetryAttempts: 3
      waitDuration: 200
      retryExceptions:
        - org.springframework.web.client.RestClientException

    backendB:
      maxRetryAttempts: 3
      waitDuration: 200
      retryExceptions:
        - org.springframework.web.client.RestClientException
```

What do you think of adding a `baseConfig` and `default` to Retry?

**Comment by RobWin** [comment]
It's alreadt possible for retry.

**Comment by RobWin** [comment]
I updated the demo. 
https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/resources/application.yml#L58-L72

**Comment by Macarse** [comment]
@RobWin Thanks!

**Comment by Macarse** [comment]
@RobWin I just found you can do empty maps with `{}`.
My config now looks like this:

```
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 200
      retryExceptions:
        - org.springframework.web.client.RestClientException

  backends:
    backendA: {}
    backendB: {}
```
