### ISSUE TITLE
registerHealthIndicator defined in CB default is not read by the backend cfg

### ISSUE THREAD

**Issue by Macarse** [resilience4j/resilience4j#469]
When using the following cfg:

```
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: false
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10
      failureRateThreshold: 30
      eventConsumerBufferSize: 10
  backends:
    backendA:
      baseConfig: default
```

`backendACircuitBreaker` is shown in the `/health` endpoint when it shouldn't.

To make it work, I ended up moving `registerHealthIndicator: false` to the backend cfg

```
backends:
    backendA:
      baseConfig: default
      registerHealthIndicator: false
```

and `backendACircuitBreaker` disappeared
