### ISSUE TITLE
@RateLimiter is not working

### ISSUE THREAD

**Issue by HLTan94** [resilience4j/resilience4j#479]
I am trying to implement RateLimiter in my project. However, during my testing, I found out that it's not working. From my understanding, with these configurations, I should hit error after 5 calls.
```
resilience4j.limiter:
    backends:
        backendA:
            limitForPeriod: 5
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
```
However, I can still call that endpoint as many times as I wish after adding @RateLimiter to the method that I am invoking.

I modified _BackendAConnector.class_ in this [demo ](https://github.com/RobWin/resilience4j-spring-boot-demo)project to be like this 
```
@CircuitBreaker(name = "backendA")
@RateLimiter(name = "backendA")
@Component(value = "backendAConnector")
public class BackendAConnector implements Connector {

    @Override
    public String failure() {
        throw new HttpServerErrorException(HttpStatus.INTERNAL_SERVER_ERROR, "This is a remote exception");
    }

    @Override
    public String ignoreException() {
        throw new BusinessException("This exception is ignored by the CircuitBreaker of backend A");
    }

    @Override
    public String success() {
        return "Hello World from backend A";
    }

    @Override
    public Observable<String> methodWhichReturnsAStream() {
        return Observable.never();
    }
}
```

**Comment by RobWin** [comment]
Hi sry,
It's a mistake in the documentation&demo.
Its confusing and will be adapted soon.

Currently it is:

```
resilience4j.ratelimiter:
    limiters:
        backendA:
            limitForPeriod: 5
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
```
