### ISSUE TITLE
Spring rate limiter configuration question

### ISSUE THREAD

**Issue by dalexander01** [resilience4j/resilience4j#491]
Hope it's ok that I ask this question here. In the documentation it gives this as an example to configure rate limiters, using the label 'limiters' to identify configurations for different backends:

```
resilience4j.ratelimiter:
    limiters:
        backendA:
            limitForPeriod: 10
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
```

However, in the other module, instead of "limiters" they use "backends" to configure different configs for different backends or systems or whatever. This seems inconsistent. In the spring demo repo instead of "limiters" or "backends" it uses "instances

```
resilience4j.ratelimiter:
    ratelimiterAspectOrder: 2
    configs:
        default:
            limitForPeriod: 10
    instances:
        backendA:
            limitForPeriod: 10
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        backendB:
            limitForPeriod: 6
            limitRefreshPeriodInMillis: 500
            timeoutInMillis: 3000
```

Does it matter what label we use to define different configurations for different backends?
