### ISSUE TITLE
Spring Retry with no exception [question]

### ISSUE THREAD

**Issue by dalexander01** [resilience4j/resilience4j#514]
So I'm using a third party API that instead of throwing an exception when it times out or something goes wrong, it returns false. What would be the preferred way of adding a retry to this using the spring annotations?

I was thinking to possibly wrap the API call in another class that just returns an exception instead of false so that methods that use wrapper can annotate with retry as usual. Is there a better option?

**Comment by RobWin** [comment]
That's one option, but could also configure a result predicate class in the properties file.

**Comment by dalexander01** [comment]
Ok cool. There isn't an example of doing result predicates in the spring portion in the user guide so I wasn't sure if it was only available using the functional API or not, or how to use it. Do you mind giving me a quick example?

**Comment by RobWin** [comment]
Implement a Predicate like

```
public class OnErrorPredicate implements Predicate<String> {
    @Override
    public boolean test(String s) {
        return s.equals("Hello World from backend A");
    }
}
```

and then configure it like:

```
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 3
            resultPredicate: io.github.robwin.predicates.OnErrorPredicate
```
