### ISSUE TITLE
Spring Boot: Retry logic is never called when CircuitBreaker specifies a fallback

### ISSUE THREAD

**Issue by evgri243** [resilience4j/resilience4j#558]
## I'm submitting a ...
  - [x] bug report
  - [x] documentation issue
  - [ ] feature request

_Looking for a workaround?_ Check **Workaround** below.

## What is the current behaviour?

When you apply both `@Retry` and `@CircuitBreaker` annotations with fallbacks, retry logic is never called. Bellow is a slightly modified sample from the [Getting Started guide](https://resilience4j.readme.io/v0.15.0/docs/getting-started-3) to make this behaviour clearer.

```java
@CircuitBreaker(name = BACKEND, fallbackMethod = "fallback_CB")
@Retry(name = BACKEND, fallbackMethod = "fallback_Retry")
public Mono<String> method(String param1) {
   return Mono.error(new NumberFormatException());
}

private Mono<String> fallback_Retry(String param1, RuntimeException e) {
  return Mono.just("test");
}

private Mono<String> fallback_CB(String param1, RuntimeException e) {
  return Mono.just("test");
}
```

Let's create a new Spring Boot 2 application with a service like above. Then such a behavior might be observed:

  - if `method` succeeds then neither retry nor circuit breaker logic is called. _(as expected)_
  - if `method` fails then `fallback_CB` is called immediately, returns successfully and call finishes without calling any retry logic.
  - if at some point circuit breaker get open, then after `method` had fails, `fallback_CB` is called immediately, returns successfully and call finishes without calling any retry logic. _(as expected)_
  - if keep only `@Retry(...)` annotation, then on `method`'s constant failure, `method` is called for the specified amount of times and then `fallback_Retry` is called to finish it gracefully. _(as expected)_
  - if you keep only `@CircuitBreaker(...)` annotation, then after `method` fails, `fallback_CB` is called immediately _(expected or not?)_
  - if you keep everything as is and drop only `@CircuitBreaker` fallback, then retry logic works just fine and circuit breaker opens accordingly to config. But even with circuit breaker open retry makes all the "cursed to fail" calls (that might take up to a minute or so with exponential timeouts).

## What is the expected behavior?

Ideally, with circuit breaker closed and a lot of calls left to make it open, logical behavior for the code above should be like that:

  - When `method` invocation fails, retry logic is called according to configuration.
  - When all retry attempts wasted, `fallback_Retry` is called to finish the call gracefully with fallback logic.
  - If at some stage during retries circuit breaker turns open, then the next retry attempt gets intercepted and `fallback_CB` is called to finish it successfully (from retry perspective).
  - While circuit breaker is in open state, all retry call gets immediately intercepted by circuit breaker and successfully finished by `fallback_CB`.

## Steps to reproduce

Follow [Spring Boot Get Started Guide](https://resilience4j.readme.io/docs/getting-started-3) and then check the behavior.

Note, that [backing repo](https://github.com/resilience4j/resilience4j-spring-boot2-demo/tree/master/src/main/java/io/github/robwin/connnector) for the guide doesn't use fallback specification at all.

## Workaround

(for anyone searching for a solution)

After a full day of debugging and research, I was able to find a pretty nice solution that makes logic work as expected (was it intended, but not documented?).

To make it work, just change exception variable in `fallback_CB` to `CallNotPermittedException` type. Circuit breaker normally uses this exception type to notify calling code that its state is open and invocation is impossible to complete.

According to docs, fallback is called only when there is a cast from real exception to the one specified as parameter, otherwise circuit breaker throws it farther through the call stack. As in our case "Retry" is a sort of a caller, it will catch the exception and retry according to its logic. Otherwise, if circuit breaker is open, `fallback_CB` will be called intercepting any further retry attempts and making fallback instantaneous.

```java
@CircuitBreaker(name = BACKEND, fallbackMethod = "fallback_CB")
@Retry(name = BACKEND, fallbackMethod = "fallback_Retry")
public Mono<String> method(String param1) {
   return Mono.error(new NumberFormatException());
}

private Mono<String> fallback_Retry(String param1, RuntimeException e) {
  return Mono.just("test");
}

private Mono<String> fallback_CB(String param1, <em>CallNotPermittedException e</em>) {
  return Mono.just("test");
}
```

## Proposal

 - Make Circuit Breaker's fallback call fire only while open, ignoring failures in other cases (breaking change) **or**
 - Create additional "openFallback" parameter for that specific logic **or**
 - Fix the docs to use `CallNotPermittedException` in the example.

## My environment:
  
  - resilience4j: 1.17.0
  - Spring Boot: 2.1.6
  - Java SDK (Oracle): 12

**Comment by RobWin** [comment]
Hi,

thank you for this well-structured issue.
Your workaround is not a workaround. It's exactly how it was designed.

But you are right, we should add an example in our documentation to make it more clear.

If you use `@Retry` and `@CircuitBreaker` together, I would suggest you to add `CallNotPermittedException` to the list of ignored exceptions in your retry configuration. It prevents retry from making unnecessary retry attemtps.

**Comment by evgri243** [comment]
@RobWin, Thank you.

But in the case of ignoring exception it won't call retry's fallback, that doesn't meet expectations.

As for an example or docs, it's needed. I googled the whole internet looking for a solution or ideas, but found nothing at all.  Looks like no one ever tried to do that... That's crazy. Maybe I'm bad at googling? Docs didn't helped me either to get that design.

Thankfully, my IDE allows to debug external libraries, so I found a way to do it by debugging...

But nevertheless, thank you for an exceptional and amazing library.

**Comment by RobWin** [comment]
The fallback mechanism via annotations is very new.
If you have further questions, just ask them here. You don't have to waste your time goggling or debugging :)

**Comment by evgri243** [comment]
Thank you. Short questions then.

There is an idea to create some custom HttpClient with some common implementation and then inject different settings to make call to different endpoints. Main idea is to make resilience4j config different by service too, but as far as I understand it's impossible to achieve with annotations.

Any ideas? Switch to Fluent API for that?

**Comment by RobWin** [comment]
You mean, you want to create a BackendAClient, BackendBClient, .. and all of them use the custom HttpClient with different settings internally?

**Comment by evgri243** [comment]
Yes, like that. The whole logic is to keep all resilience logic in HttpClient for that and make it choose resilience config for its methods based on somehow supplied service name ("BackendA", "BackendB" and etc). Let's abstract and assume that it has only 4 methods: get(string uri), post(string uri, object body), put(string uri, object body), delete(string uri).

It's more like an abstract idea on separation of concerns, clarification depends on possibilities and implementation.

PS. Didn't intent to bring huge off-topic to the thread. But to make easier, it's still supposed to be on Spring Boot, as configurable as possible through application.yml and do Circuit Breaker and Retry as the main code.

**Comment by RobWin** [comment]
Yes, you are right. The annotations are not dynamic. They have a static service name. But you can achieve your goal with 1 decorator class for your HttpClient. That way the HttpClient is not mixed with resilience code.

**Comment by dlsrb6342** [comment]
@evgri243 

By default, `CircuitBreakerAspect` is more higher order than `RateLimiterAspect`. I think If you set more higher order to `RateLimiterAspect`, it will work as you expected.
```java
// default aspect order
private int circuitBreakerAspectOrder = Ordered.LOWEST_PRECEDENCE - 2;
private int rateLimiterAspectOrder = Ordered.LOWEST_PRECEDENCE - 1;
```

**Comment by EduardoFLima** [comment]
Just had the same struggle. Thanks!

**Comment by rusyasoft** [comment]
Sorry For bringing up this issue again, I have two questions here

---> Question-1

First I have solved the problem the way @evgri243 (he thought its a workaround but it wasn't), by having two fallbacks (fallback_Retry and fallback_CB). But when you have too many methods to apply, its becoming annoying. I mean adding two fallback methods per each method.

I have tried multiple variations but ending up with two cases:
1) it keeps retrying no matter what (even when it is in OPEN state)
2) No retry at all (Even when we are in HALF-OPEN state)

May be I'm doing it wrong, thats why is there a way to do following, with single fallbackFunc:

CLOSED STATE) No retry, Everything is OK
HALF-OPEN STATE) Retry N-times: 
  - Failed N-times and state didn't change then trigger fallbackFunc
  - Failed M-times (N < M) and the state changed to OPEN, then trigger fallbackFunc
OPEN STATE) No retry, trigger fallbackFunc

---> Question-2

@dlsrb6342  You said, we can change the order of CircuitBreakerAspect. Can you elaborate more on that topic?  Because after trying many variations, I thought maybe changing the order of those exceptions could do the trick. Anyway, I wanna hear more about this feature of changing aspect's order for the future usage :)

**Comment by dlsrb6342** [comment]
@rusyasoft 
you can change aspect order by properties.
```yaml
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 100 
  retry:
    retry-aspect-order: 1000
```

**Comment by PavloChechehov** [comment]
Hi, @dlsrb6342. Could you please provide information where you found this information about aspect. Because, in the documentation I see: https://resilience4j.readme.io/docs/getting-started-3#aspect-order. By default
![Screenshot 2022-01-18 at 12 28 46](https://user-images.githubusercontent.com/12582984/149919987-ba03fe59-904d-4c3c-bab8-6b4530056fa4.png)
![Screenshot 2022-01-18 at 12 28 39](https://user-images.githubusercontent.com/12582984/149920045-10ec9b90-08cd-4c96-a623-3683e7e46993.png)
, that means that Retry is lower than the CB.

**Comment by PavloChechehov** [comment]
@evgri243 Thank you for raising this problem!

**Comment by RobWin** [comment]
Do the described solution not work for you?

```` 
@CircuitBreaker(name = BACKEND, fallbackMethod = "fallback_CB")
@Retry(name = BACKEND, fallbackMethod = "fallback_Retry")
public Mono<String> method(String param1) {
   return Mono.error(new NumberFormatException());
}

private Mono<String> fallback_Retry(String param1, RuntimeException e) {
  return Mono.just("test");
}

private Mono<String> fallback_CB(String param1, <em>CallNotPermittedException e</em>) {
  return Mono.just("test");
}
````

**Comment by RobWin** [comment]
Even simpler would be to add `CallNotPermittedException` to the list of ignored exceptions and just use:

```
@CircuitBreaker(name = BACKEND)
@Retry(name = BACKEND, fallbackMethod = "fallback_Retry")
public Mono<String> method(String param1) {
   return Mono.error(new NumberFormatException());
}

private Mono<String> fallback_Retry(String param1, CallNotPermittedException e) {
  return Mono.just("test");
}

```

**Comment by kanbalagan** [comment]
Kind of having similar issue using the combination of FeignClient, CircuitBreaker and Retry in Spring Boot 3.3 with Spring Cloud 5.5
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-circuitbreaker-spring-retry</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>
```
The chaining works as `Retry(CircuitBreaker(FallbackFactory(Function)))` even having aspect order as
```
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 100
  retry:
    retry-aspect-order: 300
```
when there is a Feign Client exception, CircuitBreaker is handing the exception by calling the Feign Client FallbackFactory (no fallback is defined either in Retry or CircuitBreaker), here is the Feign Client annotation definition, I did not have any other annotations in Feign Client interface, settings are configured in spring config yaml file
```
@FeignClient(name = "some-name", url = "some-url", configuration = ClientConfig.class, fallbackFactory = ClientFallbackFactory.class)
```
```
spring:
  cloud:
    openfeign:
      httpclient:
        time-to-live: 10
        time-to-live-unit: seconds
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 15000
            loggerLevel: basic
      circuitbreaker:
        enabled: true
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 100
    configs:
      default:
        minimumNumberOfCalls: 10
        slidingWindowSize: 20
    instances:
      client-name:
        base-config: default
        record-exceptions:
          - java.io.IOException
          - feign.FeignException
          - feign.RetryableException
    metrics:
      enabled: false
  retry:
    retry-aspect-order: 300
    configs:
      default:
        max-attempts: 3
        enable-exponential-backoff: true
        enable-randomized-wait: true
        wait-duration: 5000
        exponential-backoff-multiplier: 2
        randomized-wait-factor: .9
    instances:
      defaultRetry:
        base-config: default
      client-name:
        retry-exceptions:
          - java.io.IOException
          - feign.FeignException
          - feign.RetryableException
        ignore-exceptions:
          - feign.FeignException$BadRequest
```
Please help build the resiliency as `FallbackFactory(Retry(CircuitBreaker(Feign Client Function)))`
