### ISSUE TITLE
How to use circuit breaker and retry annotations in reactive application ?

### ISSUE THREAD

**Issue by sazerty** [resilience4j/resilience4j#883]
I would like to use Circuit Breaker and Retry in a micro-service architecture. 
My micro-services returns Mono objects, and I can't find out an example to explain how to use Circuit Breaker and Retry in this.
```
@CircuitBreaker(name="ms")
@Retry(name="ms")
public Mono<Ms> getMs(){
		return webClientBuilder.build().get()
				.uri("http://load-balanced-ms/get-ms").retrieve().bodyToMono(Ms.class);
	}
```
Can you help me ?
Thanks a lot

**Comment by RobWin** [comment]
Hi, yes that's the correct usage. What doesn't work for you? Do you use the Spring Boot 2 Starter?

**Comment by sazerty** [comment]
Yes I have Spring Boot 2 Starter. Here's my POM.xml :
```
<dependencies>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>Hoxton.SR2</version>
			<type>pom</type>
		</dependency>
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-config</artifactId>
		    <version>2.2.1.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-loadbalancer</artifactId>
		    <version>2.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
			<version>2.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway</artifactId>
			<version>2.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-circuitbreaker</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-reactor</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-retry</artifactId>
			<version>1.3.1</version>
		</dependency>
	</dependencies>
```
If I have one instance of my micro-service which is down (Error 500),, requests are still send to it and circuit breaker and retry has no effect.
Thanks

**Comment by RobWin** [comment]
How did you configure it?

**Comment by sazerty** [comment]
Here's my application.yml :
server:
```
  port: 8090

spring:
  application:
    name: application-test

  cloud:
    gateway:
      routes:
      - id: ms-service
        uri: lb://load-balanced-ms/
        predicates:
          - Path=/get-ms/**
ribbon:
  eureka:
    enabled: false
load-balanced-ms:
  ribbon:
    listOfServers: localhost:5555, localhost:5556
    ServerListRefreshInterval: 15000
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 1
      permittedNumberOfCallsInHalfOpenState: 1
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 1s
      failureRateThreshold: 10
      eventConsumerBufferSize: 10
  instances:
    ms:
      baseConfig: default
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      maxAutoRetriesNextServer: 1
  instances:
    ms:
      baseConfig: default
```
