### ISSUE TITLE
Circuit breaker not opening when @CircuitBreaker and @TimeLimiter used together

### ISSUE THREAD

**Issue by georgeharley** [resilience4j/resilience4j#902]
Resilience4j version:
1.3.1

Java version:
1.8.0_241

Spring Boot version:
2.2.5.RELEASE

If a method is annotated with `@CircuitBreaker` and `@TimeLimiter` annotations then the circuit breaker no longer seems to transition to OPEN when the failure rate is greater than the defined `failureRateThreshold`. If the `@TimeLimiter` annotation is removed from the method then the circuit breaker behaves as expected.

The below example code is based on [this demo code](https://github.com/resilience4j/resilience4j-spring-boot2-demo/blob/master/src/main/java/io/github/robwin/service/BackendAService.java#L141-L148). The annotated method is just a simple Spring Web HTTP GET handler in a `@RestController` class. Here the 100% failure fate is intentional.

```java

    // @Bulkhead(name = "mybulkhead", type = Type.THREADPOOL)
    // @TimeLimiter(name = "mytimelimiter", fallbackMethod = "getFallback")
    @CircuitBreaker(name = "mycircuitbreaker", fallbackMethod = "getFallback")
    @GetMapping("/song")
    public CompletableFuture<String> getHandler() {
        return CompletableFuture.completedFuture(getSomeStringValue());
    }

    private String getSomeStringValue() {
        throw new RuntimeException("boo!");
    }

    private CompletableFuture<String> getFallback(HttpHeaders ignore, Throwable timeout) {
        return CompletableFuture.completedFuture("fallback!");
    }

```

**With the bulk head and time limiter annotations left commented out**, when the Spring Boot Web app is started and some light load is applied from the command line (just using curl from inside a while loop) then, as expected, after a few seconds the circuit opens. Evidence of that comes courtesy of a logging event consumer added in a Boot `@Configuration` class. It logs the event `State transition from CLOSED to OPEN`.

```java

@Configuration
public class MyConfiguration {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClientConfiguration.class);

    private final CircuitBreakerRegistry circuitBreakerRegistry;

    public ClientConfiguration(CircuitBreakerRegistry circuitBreakerRegistry) {
        this.circuitBreakerRegistry = circuitBreakerRegistry;
    }

    . . .

    @PostConstruct
    public void init() {
        CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("mycircuitbreaker");
        circuitBreaker.getEventPublisher()
            .onStateTransition(event -> {
                CircuitBreaker.StateTransition transition = event.getStateTransition();
                LOGGER.info("Circuit breaker 'mycircuitbreaker' state change: {} !!!", transition);
            });
    }
}

``` 
If the application is run again **with the bulk head and time limiter annotations uncommented** and the same light request load applied then no circuit breaker state transition events are observed in the application log. 

Here's an excerpt from the **application.yml** file containing configuration of the circuit breaker, time limiter, and bulk head.

```yaml


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 1
    instances:
      mycircuitbreaker:
        baseConfig: default
        failureRateThreshold: 33

  timelimiter:
    configs:
      default:
        timeoutDuration: 2000
    instances:
      mytimelimiter:
        baseConfig: default
        timeoutDuration: 5000
        cancelRunningFuture: true

  bulkhead:
    instances:
       mybulkhead:
         maxConcurrentCalls: 10
         maxWaitDuration: 100ms

```

I'm very new to Resilience4J so may well be making a very basic error. Just can't spot it.
