### ISSUE TITLE
Limitation with annotations

### ISSUE THREAD

**Issue by thash06** [resilience4j/resilience4j#930]
Resilience4j version:1.3.3

Java version:1.8

I have explored both the code based configuration approach as well as the annotation based approach to defining the decorators around service calls.
I noticed that with annotation we cannot do every configuration that is available through code. For example in Retry I can create a config with exponential backof quite easily.

```
    private RetryConfig createRetryConfig() {
        IntervalFunction intervalWithCustomExponentialBackoff = IntervalFunction
                .ofExponentialBackoff(500l, 5d);
        return RetryConfig.custom()
                .intervalFunction(intervalWithCustomExponentialBackoff)
                .maxAttempts(5)
                .retryExceptions(ConnectException.class, ResourceAccessException.class)
                .build();
    }
```

But the same exponential backoff somehow cannot be created using annotations and yml tags

#Yml snippet
```
resilience4j.retry:
  configs:
    default:
      waitDuration: 1000
      maxRetryAttempts: 10
      retryExceptions:
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
        - java.net.ConnectException
  instances:
    data-service:
      baseConfig: default
```

When I try adding tags for intervalFunction under **resilience4j.retry** they were ignored. Am I doing something wrong or are these not supported?

**Comment by RobWin** [comment]
Try:

```
resilience4j.retry:
  configs:
    default:
            waitDuration: 500
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 5
```
