### ISSUE TITLE
actuator shows Whitelabel error page with "Invalid Event"

### ISSUE THREAD

**Issue by rusyasoft** [resilience4j/resilience4j#939]
Resilience4j version: 1.3.1

Java version: 1.8

I've been trying resilience4j-spring-boot2-demo example, with implementation "io.github.resilience4j:resilience4j-retrofit:1.3.1"

```java
private static final String BACKEND_MINE = "backendMine";

@Retry(name = BACKEND_MINE, fallbackMethod = "getMineFallback2")
@CircuitBreaker(name = "getMineSuccessName", fallbackMethod = "getMineFallback")
public MineResponse getMine(final String userId, final Integer contentId) throws IOException {
    OutCome<MineResponse> resultResponse = RetrofitUtil.resilentProcess(mineCalls.getMineSuccess());
    if (resultResponse != null) {
        return resultResponse.getResult();
    }
    return null;
}

private MineResponse getMineFallback(final String userId, final Integer contentId, CallNotPermittedException ex) {
    MineResponse mineResponse = new MineResponse();
    mineResponse.setField1(1);
    mineResponse.setField2(1);
    System.out.println("fallback exception ->  " + ex.getMessage() + " ex: " + ex);
    return mineResponse;
}

private MineResponse getMineFallback2(final String userId, final Integer contentId, Exception ex) {
    MineResponse mineResponse = new MineResponse();
    mineResponse.setField1(1);
    mineResponse.setField2(1);
    System.out.println("fallback2 exception ->  " + ex.getMessage() + " ex: " + ex);
    return mineResponse;
}
```
names at Annotation:
getMineSuccessName - has no configuration at all
backendMine - has following configuration in application.yml

application.yml
```YAML
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 3
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException

            ignoreExceptions:
                - io.github.robwin.exception.BusinessException
    instances:
        backendA:
            baseConfig: default
        backendB:
            baseConfig: default
        backendMine:
            maxRetryAttempts: 3
            waitDuration: 100
            ignoreExceptions:
                - io.github.robwin.exception.BusinessException
```

When I run this application, everything seem works fine as expected. When other side is not responding and I call getMine() twise the /actuator/circuitbreakerevents shows "Whitelabel Error Page" with Invalid event. 

When I debug this situation somehow I hapened to reach CircuitBreakerOnFailureRateExceededEvent.getEventType() where returned type is Type.FAILURE_RATE_EXCEEDED. 
So it is invalid event for the CircuitBreakerEventDTOFactory.createCircuitBreakerEventDTO().

By the way, when I just kept calling getMine(...) for sometime, then /actuator/circuitbreakerevents started working well again. This "invalid event" error happens only at the beginning (after 2 calls)

Is this bug, or am I doing something wrong ?
