### ISSUE TITLE
record exceptions configurations for instance not working in Spring Boot2

### ISSUE THREAD

**Issue by SeliMeli** [resilience4j/resilience4j#941]
Resilience4j version: 1.3.1

Java version: Java 8

Spring Boot 2 Version: 2.1.4.RELEASE

record exceptions configuration for instance is not working:
```
resilience4j.circuitbreaker.instances.A            = org.springframework.web.client.HttpServerErrorException
```
is not injected to circuit breaker config when init circuit breaker. But when put those config to default scope it works.

**Comment by RobWin** [comment]
Hi, is this the correct config snippet you wanted to share?
The snippet is missing the property name.

**Comment by SeliMeli** [comment]
oops, sry, copy mistake. here is the correct version
```resilience4j.circuitbreaker.instances.A.record-exceptions =org.springframework.web.client.HttpServerErrorException```

**Comment by dlsrb6342** [comment]
Hi @SeliMeli 

I tested with [resilience4j-spring-boot2-demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo). And config was put well.
```yaml
resilience4j.circuitbreaker:
    instances:
        backendC:
            record-exceptions: org.springframework.web.client.HttpServerErrorException
```
![image](https://user-images.githubusercontent.com/19386038/77817627-9ff05f80-710f-11ea-9268-6a9daaa64208.png)

Could you test with our demo?
