### ISSUE TITLE
Circuit breaker never changes state from HALF_OPEN to CLOSED on Spring Boot Cloud

### ISSUE THREAD

**Issue by ppa-xyt** [resilience4j/resilience4j#944]
Resilience4j version: 1.1.0
Dependencies:
```
<spring-boot.version>2.2.2.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR2</spring-cloud.version>

      <dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-gateway</artifactId>
	</dependency>
        <dependency>
		<groupId>io.github.resilience4j</groupId>
		<artifactId>resilience4j-spring-boot2</artifactId>
		<version>1.1.0</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>
	</dependency>
	<dependency>
		<groupId>io.github.resilience4j</groupId>
		<artifactId>resilience4j-prometheus</artifactId>
		<version>1.1.0</version>
	</dependency>
```

Java version: 1.8

Circuit breaker configuration:
```
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
      recordExceptions:
        - org.springframework.cloud.gateway.support.NotFoundException
instances:
    serviceA:
      baseConfig: default

#in routes:
- id: cb-serviceA
   uri: lb://serviceA
   predicates:
      - Path=/serviceA/**
   filters:
      - CircuitBreaker=serviceA
```

Scenario:
having gateway, eureka and serviceA. I call REST service from serviceA through gateway in this way:
`GET localhost:PORT/serviceA/endpoint`

Steps:
1. I turn the serviceA off and make 10 calls to gateway -> circuit breaker changes the state from `CLOSED` to `OPEN` (ok)
2. It stays 10 seconds in `OPEN` state (as configured) and goes to `HALF_OPEN` (ok)
3. I turn serviceA on
4. Make 10 successful calls but circuit breaker remains in `HALF_OPEN` state (not ok)
Even making more (20, 30, 40) calls but the circuit breaker still stays in `HALF_OPEN` state

It looks like success events are not recorded when in HALF_OPEN state? Or maybe my configuration is wrong? 
Appreciate your help
