### ISSUE TITLE
Question about sharedConfig in application.yaml

### ISSUE THREAD

**Issue by rgampa** [resilience4j/resilience4j#947]
Resilience4j version: 1.3.1

Java version: 1.8

In the below example will `someShared` inherit `default` config automatically OR should add `someShared.baseConfig: default` explicitly? I would like to keep it compact by using some settings from `default` configs in `someShared` and override only couple of props.

```
resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 10000
            failureRateThreshold: 60
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
        someShared:
            slidingWindowSize: 50
            permittedNumberOfCallsInHalfOpenState: 10
    instances:
        backendA:
            baseConfig: default
            waitDurationInOpenState: 5000
        backendB:
            baseConfig: someShared

```
