### ISSUE TITLE
Support configuring exponential random backoff via Spring config

### ISSUE THREAD

**Issue by internetstaff** [resilience4j/resilience4j#982]
Resilience4j version: 1.4.0

Java version: All :)

Thanks for a great project - we've recently adopted this in our Spring Boot apps.

We do find it cumbersome to need to create RetryConfigCustomizers only to be able to configure exponential backoff with random jitter. We would otherwise (so far) be able to just provision everything in our Spring config.

Would it be possible to support enabling both via RetryConfigurationProperties?  Seems like maybe enabling both exponential backoff and randomized wait could create an IntervalFunction.ofExponentialRandomBackoff instead of throwing IllegalStateException ?

Thanks!

**Comment by RobWin** [comment]
Hi,

currently you can only do

```
resilience4j.retry:
    instances:
        backendA:
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
```
